'use server';

import { createServerSupabase } from './server';

// ─── Types ───────────────────────────────────────────────────────────
export interface FormSection {
  id: number;
  title: string;
  description: string | null;
  header: string | null;
}

export interface QuestionOption {
  id: number;
  option_text: string;
  is_active: boolean;
}

export interface FormQuestion {
  id: number;
  form_question: string | null;
  subtext: string | null;
  question_type: string;
  is_required: boolean;
  is_active: boolean;
  section_id: number;
  autofill_key: string | null;
  question_key_id: number | null;
  options: QuestionOption[];
}

// ─── Form Editor Queries ─────────────────────────────────────────────

export async function fetchFormSections(): Promise<FormSection[]> {
  const supabase = createServerSupabase();
  const { data, error } = await supabase
    .from("W26_form_sections")
    .select("id, title, description, header")
    .order("id", { ascending: true });

    console.log("Fetched sections:", data);

  if (error) throw new Error("Failed to load sections: " + error.message);
  return data || [];
}


export async function fetchFormQuestions(): Promise<FormQuestion[]> {
  const supabase = createServerSupabase();
  const { data, error } = await supabase
    .from("W26_questions")
    .select(`
      id,
      form_question,
      subtext,
      question_type,
      is_required,
      is_active,
      section_id,
      autofill_key,
      question_key_id,
      W26_question_options (
        id,
        option_text,
        is_active
      )
    `);

  if (error) throw new Error("Failed to load questions: " + error.message);

  return (data || []).map((q: any) => ({
    id: q.id,
    form_question: q.form_question,
    subtext: q.subtext,
    question_type: q.question_type,
    is_required: q.is_required ?? false,
    is_active: q.is_active,
    section_id: q.section_id,
    autofill_key: q.autofill_key,
    question_key_id: q.question_key_id,
    options: (q.W26_question_options || []).filter((o: any) => o.is_active),
  }));
}

export async function saveQuestion(question: FormQuestion): Promise<void> {
  const supabase = createServerSupabase();

  const { error: updateError } = await supabase
    .from("W26_questions")
    .update({
      form_question: question.form_question,
      subtext: question.subtext,
      question_type: question.question_type,
      is_required: question.is_required,
      section_id: question.section_id,
      autofill_key: question.autofill_key,
    })
    .eq("id", question.id);

  if (updateError) throw updateError;

  // Soft-delete options that were removed
  const existingOptionIds = question.options
    .filter((o) => o.id > 0)
    .map((o) => o.id);

  if (existingOptionIds.length > 0) {
    await supabase
      .from("W26_question_options")
      .update({ is_active: false })
      .eq("question_id", question.id)
      .eq("is_active", true)
      .not("id", "in", `(${existingOptionIds.join(",")})`);
  }

  // Upsert options
  for (const opt of question.options) {
    if (opt.id > 0) {
      await supabase
        .from("W26_question_options")
        .update({ option_text: opt.option_text, is_active: true })
        .eq("id", opt.id);
    } else {
      await supabase.from("W26_question_options").insert({
        question_id: question.id,
        option_text: opt.option_text,
        is_active: true,
      });
    }
  }
}

// export async function deleteQuestion(questionId: number): Promise<void> {
//   const supabase = createServerSupabase();
//   const { error } = await supabase
//     .from("W26_questions")
//     .update({ is_active: false })
//     .eq("id", questionId);

//   if (error) throw error;
// }

export async function addQuestion(
  sectionId: number,
  maxFormorder: number,
  newQuestion: {
    form_question: string;
    subtext: string;
    question_type: string;
    is_required: boolean;
    options: string[];
  }
): Promise<void> {

  // create query to insert a row into W26_question_keys
  // 	id: autogenerated
  // 	category: foreign key to W26_questions_category that frank chooses from a dropdown maybe
  // 	question key: typed in by frank depending on what he wants but MUST be in the right format (e.g. Q52_Biological)
  // 	comment: TRUE or FALSE based on whether the question has a textbox option
  // 	definition: i think this can be left NULL

  const supabase = createServerSupabase();

  // Create question_key first
  const { data: keyData, error: keyError } = await supabase
    .from("W26_question_keys")
    .insert({ formorder: maxFormorder + 1 })
    .select("id")
    .single();

  if (keyError) throw keyError;
  
  // create query to insert a row into W26_questions
  // 	id: autogenerated i think
  // 	form_question: typed in by frank but should be in the right format (e.g. Biological Observations (Q52))
  // 	question key: foreign key to W26_question_keys's question key column
  // 	obs_value: TRUE if question has no textbox, NULL otherwise (except in some cases)
  // 	obs_comm: TRUE if question has textbox, NULL otherwise
  // 	question_key_id: foreign key to W26_question_keys's id column
  // 	question_type: determined by which option frank selected
  // 	is_active: set to TRUE
  // 	section_id: based on which section the question was added to
  // 	is_required: TRUE or FALSE based on whether the checkbox is clicked
  // 	subtext: typed in by frank
  // 	autofill_key: i think just set this to NULL
  // 	formorder: determined by where the new question is placed in (might be messy because need to update formorder for all subsequent questions)
  
  // if the question has multiple choices, create query to insert however many rows into W26_question_options as necessary
  // 	id: autogenerated i think
  // 	question_id: foreign key


  // Create question
  const { data: questionData, error: questionError } = await supabase
    .from("W26_questions")
    .insert({
      form_question: newQuestion.form_question,
      subtext: newQuestion.subtext,
      question_type: newQuestion.question_type,
      is_required: newQuestion.is_required,
      is_active: true,
      section_id: sectionId,
      question_key_id: keyData.id,
    })
    .select("id")
    .single();

  if (questionError) throw questionError;

  // Create options if applicable
  if (
    newQuestion.options.length > 0 &&
    ["option", "selectall"].includes(newQuestion.question_type)
  ) {
    const optionsToInsert = newQuestion.options
      .filter((o) => o.trim())
      .map((o) => ({
        question_id: questionData.id,
        option_text: o.trim(),
        is_active: true,
      }));

    if (optionsToInsert.length > 0) {
      const { error: optError } = await supabase
        .from("W26_question_options")
        .insert(optionsToInsert);

      if (optError) throw optError;
    }
  }
}

export async function swapQuestionOrder(
  keyId1: number,
  order1: number | null,
  keyId2: number,
  order2: number | null
): Promise<void> {
  const supabase = createServerSupabase();
  await Promise.all([
    supabase
      .from("W26_questions")
      .update({ formorder: order2 })
      .eq("id", keyId1),
    supabase
      .from("W26_questions")
      .update({ formorder: order1 })
      .eq("id", keyId2),
  ]);
}

export async function addFormSection(section: {
  title: string;
  description: string | null;
  header: string;
}): Promise<number> {
  const supabase = createServerSupabase();
  const { data, error } = await supabase
    .from("W26_form_sections")
    .insert(section)
    .select("id")
    .single();

  if (error) throw error;
  return data.id;
}
