// Generated by ChatGPT


jest.mock("next/server", () => ({
  NextResponse: {
    json: jest.fn((body, init) => ({
      status: init?.status ?? 200,
      json: async () => body,
    })),
  },
}));

import { GET } from "@/app/api/gallery/route";
import { createClient } from "@/utils/supabase/server";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

jest.mock("@/utils/supabase/server", () => ({
  createClient: jest.fn()
}));

jest.mock("@aws-sdk/client-s3", () => ({
  S3Client: jest.fn().mockImplementation(() => ({})),
  GetObjectCommand: jest.fn().mockImplementation((input) => ({ input })),
}));

jest.mock("@aws-sdk/s3-request-presigner", () => ({
  getSignedUrl: jest.fn(),
}));



describe("GET /api/gallery", () => {
  const mockGetUser = jest.fn();
  const mockFrom = jest.fn();

  beforeEach(() => {
    jest.clearAllMocks();

    (createClient as jest.Mock).mockResolvedValue({
      auth: {
        getUser: mockGetUser,
      },
      from: mockFrom,
    });
  });

  it("returns 401 if user is not authenticated", async () => {
    mockGetUser.mockResolvedValue({
      data: { user: null },
      error: null,
    });

    const response = await GET();
    const body = await response.json();

    expect(response.status).toBe(401);
    expect(body).toEqual({ error: "Unauthorized" });
  });

  it("returns 401 if auth throws an error", async () => {
    mockGetUser.mockResolvedValue({
      data: { user: null },
      error: { message: "Auth failed" },
    });

    const response = await GET();
    const body = await response.json();

    expect(response.status).toBe(401);
    expect(body).toEqual({ error: "Unauthorized" });
  });

  it("returns 403 if user is not admin", async () => {
    mockGetUser.mockResolvedValue({
      data: {
        user: {
          id: "user-1",
          user_metadata: { role: "user" },
        },
      },
      error: null,
    });

    const response = await GET();
    const body = await response.json();

    expect(response.status).toBe(403);
    expect(body).toEqual({ error: "Forbidden" });
  });

  it("returns gallery items successfully for admin", async () => {
    mockGetUser.mockResolvedValue({
      data: {
        user: {
          id: "admin-1",
          user_metadata: { role: "admin" },
        },
      },
      error: null,
    });

    const attachmentsData = [
      {
        id: "14",
        response_id: "3226",
        question_id: "27",
        caption: "Cracked Tree",
        description: "Large crack running up the trunk of a tree.",
        storage_key: "inspections/207/3226/27/file1.jpg",
        content_type: "image/jpeg",
        file_size_bytes: 2433304,
        filename: "RiverLot56_01-31-2026_ZoeP_CrackedTree.jpg",
        site_id: "207",
      },
      {
        id: "15",
        response_id: "3227",
        question_id: "28",
        caption: "Trail Damage",
        description: "Visible ATV tracks.",
        storage_key: "inspections/208/3227/28/file2.jpg",
        content_type: "image/png",
        file_size_bytes: 123456,
        filename: "TrailDamage.png",
        site_id: "208",
      },
    ];

    const sitesData = [
      { id: "207", namesite: "Riverlot 56 (NA)" },
      { id: "208", namesite: "Clyde Fen" },
    ];

    const attachmentsOrderMock = jest.fn().mockResolvedValue({
      data: attachmentsData,
      error: null,
    });

    const attachmentsInMock = jest.fn().mockReturnValue({
      order: attachmentsOrderMock,
    });

    const attachmentsSelectMock = jest.fn().mockReturnValue({
      in: attachmentsInMock,
    });

    const sitesInMock = jest.fn().mockResolvedValue({
      data: sitesData,
      error: null,
    });

    const sitesSelectMock = jest.fn().mockReturnValue({
      in: sitesInMock,
    });

    mockFrom.mockImplementation((table: string) => {
      if (table === "W26_attachments") {
        return {
          select: attachmentsSelectMock,
        };
      }

      if (table === "W26_sites-pa") {
        return {
          select: sitesSelectMock,
        };
      }

      throw new Error(`Unexpected table: ${table}`);
    });

    (getSignedUrl as jest.Mock)
      .mockResolvedValueOnce("https://signed-url.example.com/file1.jpg")
      .mockResolvedValueOnce("https://signed-url.example.com/file2.png");

    const response = await GET();
    const body = await response.json();

    expect(response.status).toBe(200);

    expect(mockFrom).toHaveBeenCalledWith("W26_attachments");
    expect(mockFrom).toHaveBeenCalledWith("W26_sites-pa");

    expect(attachmentsInMock).toHaveBeenCalledWith("content_type", [
      "image/jpeg",
      "image/png",
      "image/webp",
    ]);

    expect(sitesInMock).toHaveBeenCalledWith("id", ["207", "208"]);

    expect(body).toEqual({
      items: [
        {
          id: "14",
          response_id: "3226",
          question_id: "27",
          caption: "Cracked Tree",
          description: "Large crack running up the trunk of a tree.",
          storage_key: "inspections/207/3226/27/file1.jpg",
          content_type: "image/jpeg",
          file_size_bytes: 2433304,
          filename: "RiverLot56_01-31-2026_ZoeP_CrackedTree.jpg",
          site_id: "207",
          site_name: "Riverlot 56 (NA)",
          imageUrl: "https://signed-url.example.com/file1.jpg",
        },
        {
          id: "15",
          response_id: "3227",
          question_id: "28",
          caption: "Trail Damage",
          description: "Visible ATV tracks.",
          storage_key: "inspections/208/3227/28/file2.jpg",
          content_type: "image/png",
          file_size_bytes: 123456,
          filename: "TrailDamage.png",
          site_id: "208",
          site_name: "Clyde Fen",
          imageUrl: "https://signed-url.example.com/file2.png",
        },
      ],
    });
  });

  it("filters out items when signed URL generation fails", async () => {
    mockGetUser.mockResolvedValue({
      data: {
        user: {
          id: "admin-1",
          user_metadata: { role: "admin" },
        },
      },
      error: null,
    });

    const attachmentsData = [
      {
        id: "14",
        response_id: "3226",
        question_id: "27",
        caption: "Cracked Tree",
        description: "desc",
        storage_key: "inspections/207/3226/27/file1.jpg",
        content_type: "image/jpeg",
        file_size_bytes: 2433304,
        filename: "file1.jpg",
        site_id: "207",
      },
      {
        id: "15",
        response_id: "3227",
        question_id: "28",
        caption: "Trail Damage",
        description: "desc2",
        storage_key: "inspections/208/3227/28/file2.jpg",
        content_type: "image/png",
        file_size_bytes: 123456,
        filename: "file2.png",
        site_id: "208",
      },
    ];

    const sitesData = [
      { id: "207", namesite: "Riverlot 56 (NA)" },
      { id: "208", namesite: "Clyde Fen" },
    ];

    const attachmentsOrderMock = jest.fn().mockResolvedValue({
      data: attachmentsData,
      error: null,
    });

    const attachmentsInMock = jest.fn().mockReturnValue({
      order: attachmentsOrderMock,
    });

    const attachmentsSelectMock = jest.fn().mockReturnValue({
      in: attachmentsInMock,
    });

    const sitesInMock = jest.fn().mockResolvedValue({
      data: sitesData,
      error: null,
    });

    const sitesSelectMock = jest.fn().mockReturnValue({
      in: sitesInMock,
    });

    mockFrom.mockImplementation((table: string) => {
      if (table === "W26_attachments") {
        return {
          select: attachmentsSelectMock,
        };
      }

      if (table === "W26_sites-pa") {
        return {
          select: sitesSelectMock,
        };
      }

      throw new Error(`Unexpected table: ${table}`);
    });

    (getSignedUrl as jest.Mock)
      .mockResolvedValueOnce("https://signed-url.example.com/file1.jpg")
      .mockRejectedValueOnce(new Error("S3 failed"));

    const response = await GET();
    const body = await response.json();

    expect(response.status).toBe(200);
    expect(body.items).toHaveLength(1);
    expect(body.items[0].id).toBe("14");
  });

  it("returns 500 if attachments query fails", async () => {
    mockGetUser.mockResolvedValue({
      data: {
        user: {
          id: "admin-1",
          user_metadata: { role: "admin" },
        },
      },
      error: null,
    });

    const attachmentsOrderMock = jest.fn().mockResolvedValue({
      data: null,
      error: { message: "Failed to fetch attachments" },
    });

    const attachmentsInMock = jest.fn().mockReturnValue({
      order: attachmentsOrderMock,
    });

    const attachmentsSelectMock = jest.fn().mockReturnValue({
      in: attachmentsInMock,
    });

    mockFrom.mockImplementation((table: string) => {
      if (table === "W26_attachments") {
        return {
          select: attachmentsSelectMock,
        };
      }

      throw new Error(`Unexpected table: ${table}`);
    });

    const response = await GET();
    const body = await response.json();

    expect(response.status).toBe(500);
    expect(body).toEqual({ error: "Failed to fetch attachments" });
  });

  it("returns 500 if sites query fails", async () => {
    mockGetUser.mockResolvedValue({
      data: {
        user: {
          id: "admin-1",
          user_metadata: { role: "admin" },
        },
      },
      error: null,
    });

    const attachmentsData = [
      {
        id: "14",
        response_id: "3226",
        question_id: "27",
        caption: "Cracked Tree",
        description: "desc",
        storage_key: "inspections/207/3226/27/file1.jpg",
        content_type: "image/jpeg",
        file_size_bytes: 2433304,
        filename: "file1.jpg",
        site_id: "207",
      },
    ];

    const attachmentsOrderMock = jest.fn().mockResolvedValue({
      data: attachmentsData,
      error: null,
    });

    const attachmentsInMock = jest.fn().mockReturnValue({
      order: attachmentsOrderMock,
    });

    const attachmentsSelectMock = jest.fn().mockReturnValue({
      in: attachmentsInMock,
    });

    const sitesInMock = jest.fn().mockResolvedValue({
      data: null,
      error: { message: "Failed to fetch sites" },
    });

    const sitesSelectMock = jest.fn().mockReturnValue({
      in: sitesInMock,
    });

    mockFrom.mockImplementation((table: string) => {
      if (table === "W26_attachments") {
        return {
          select: attachmentsSelectMock,
        };
      }

      if (table === "W26_sites-pa") {
        return {
          select: sitesSelectMock,
        };
      }

      throw new Error(`Unexpected table: ${table}`);
    });

    const response = await GET();
    const body = await response.json();

    expect(response.status).toBe(500);
    expect(body).toEqual({ error: "Failed to fetch sites" });
  });

  it("returns 500 on unexpected exception", async () => {
    mockGetUser.mockRejectedValue(new Error("Unexpected auth crash"));

    const response = await GET();
    const body = await response.json();

    expect(response.status).toBe(500);
    expect(body).toEqual({ error: "Failed to load gallery" });
  });
});