// Generated by ChatGPT

jest.mock("next/server", () => ({
  NextResponse: {
    json: jest.fn((body, init) => ({
      status: init?.status ?? 200,
      json: async () => body,
    })),
  },
}));

import { GET } from "@/app/api/homepage-images/[siteId]/route";
import { createClient } from "@/utils/supabase/server";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

jest.mock("@/utils/supabase/server", () => ({
  createClient: jest.fn(),
}));

jest.mock("@aws-sdk/client-s3", () => ({
  S3Client: jest.fn().mockImplementation(() => ({})),
  GetObjectCommand: jest.fn().mockImplementation((input) => ({ input })),
}));

jest.mock("@aws-sdk/s3-request-presigner", () => ({
  getSignedUrl: jest.fn(),
}));

const makeParams = (siteId: string) =>
  ({ params: Promise.resolve({ siteId }) } as any);

describe("GET /api/homepage-images/[siteId]", () => {
  const mockGetUser = jest.fn();
  const mockFrom = jest.fn();

  beforeEach(() => {
    jest.clearAllMocks();

    (createClient as jest.Mock).mockResolvedValue({
      auth: { getUser: mockGetUser },
      from: mockFrom,
    });
  });

  it("returns 400 when siteId is missing", async () => {
    const response = await GET(new Request("http://localhost"), makeParams(""));
    const body = await response.json();

    expect(response.status).toBe(400);
    expect(body).toEqual({ error: "Invalid site id" });
  });

  it("returns 400 when siteId is not a number", async () => {
    const response = await GET(new Request("http://localhost"), makeParams("abc"));
    const body = await response.json();

    expect(response.status).toBe(400);
    expect(body).toEqual({ error: "Invalid site id" });
  });

  it("returns 401 when user is not authenticated", async () => {
    mockGetUser.mockResolvedValue({
      data: { user: null },
      error: null,
    });

    const response = await GET(new Request("http://localhost"), makeParams("207"));
    const body = await response.json();

    expect(response.status).toBe(401);
    expect(body).toEqual({ error: "Unauthorized" });
  });

  it("returns 401 when auth errors", async () => {
    mockGetUser.mockResolvedValue({
      data: { user: null },
      error: { message: "Auth failed" },
    });

    const response = await GET(new Request("http://localhost"), makeParams("207"));
    const body = await response.json();

    expect(response.status).toBe(401);
    expect(body).toEqual({ error: "Unauthorized" });
  });

  it("returns 500 when uploads query fails", async () => {
    mockGetUser.mockResolvedValue({
      data: { user: { id: "user-1" } },
      error: null,
    });

    const uploadsOrderMock = jest.fn().mockResolvedValue({
      data: null,
      error: { message: "DB error" },
    });

    const uploadsEqMock = jest.fn().mockReturnValue({
      order: uploadsOrderMock,
    });

    const uploadsSelectMock = jest.fn().mockReturnValue({
      eq: uploadsEqMock,
    });

    mockFrom.mockImplementation((table: string) => {
      if (table === "W26_homepage-image-uploads") {
        return {
          select: uploadsSelectMock,
        };
      }
      throw new Error(`Unexpected table: ${table}`);
    });

    const response = await GET(new Request("http://localhost"), makeParams("207"));
    const body = await response.json();

    expect(response.status).toBe(500);
    expect(body).toEqual({ error: "DB error" });
    expect(uploadsEqMock).toHaveBeenCalledWith("site_id", 207);
  });

  it("returns empty items when no uploads exist for site", async () => {
    mockGetUser.mockResolvedValue({
      data: { user: { id: "user-1" } },
      error: null,
    });

    const uploadsOrderMock = jest.fn().mockResolvedValue({
      data: [],
      error: null,
    });

    const uploadsEqMock = jest.fn().mockReturnValue({
      order: uploadsOrderMock,
    });

    const uploadsSelectMock = jest.fn().mockReturnValue({
      eq: uploadsEqMock,
    });

    const siteSingleMock = jest.fn().mockResolvedValue({
      data: { namesite: "Riverlot 56 (NA)" },
      error: null,
    });

    const siteEqMock = jest.fn().mockReturnValue({
      single: siteSingleMock,
    });

    const siteSelectMock = jest.fn().mockReturnValue({
      eq: siteEqMock,
    });

    mockFrom.mockImplementation((table: string) => {
      if (table === "W26_homepage-image-uploads") {
        return {
          select: uploadsSelectMock,
        };
      }
      if (table === "W26_sites-pa") {
        return {
          select: siteSelectMock,
        };
      }
      throw new Error(`Unexpected table: ${table}`);
    });

    const response = await GET(new Request("http://localhost"), makeParams("207"));
    const body = await response.json();

    expect(response.status).toBe(200);
    expect(body).toEqual({ items: [] });
    expect(getSignedUrl).not.toHaveBeenCalled();
    expect(siteEqMock).toHaveBeenCalledWith("id", 207);
  });

  it("returns items with signed URLs and correct fields", async () => {
    mockGetUser.mockResolvedValue({
      data: { user: { id: "user-1" } },
      error: null,
    });

    const mockUpload = {
      id: 14,
      site_id: 207,
      user_id: "user-1",
      date: "2026-03-17",
      photographer: "Vishal Sivakumar",
      identifier: "CMPUT401W26 Visit",
      caption: "Riverlot56 Visit with Frank Potter!",
      storage_key: "homepage-image-uploads/207/user-1/tree-A1B2C3D4.jpg",
      filename: "tree-A1B2C3D4.jpg",
      content_type: "image/jpeg",
      file_size_bytes: 111111,
    };

    const uploadsOrderMock = jest.fn().mockResolvedValue({
      data: [mockUpload],
      error: null,
    });

    const uploadsEqMock = jest.fn().mockReturnValue({
      order: uploadsOrderMock,
    });

    const uploadsSelectMock = jest.fn().mockReturnValue({
      eq: uploadsEqMock,
    });

    const siteSingleMock = jest.fn().mockResolvedValue({
      data: { namesite: "Riverlot 56 (NA)" },
      error: null,
    });

    const siteEqMock = jest.fn().mockReturnValue({
      single: siteSingleMock,
    });

    const siteSelectMock = jest.fn().mockReturnValue({
      eq: siteEqMock,
    });

    mockFrom.mockImplementation((table: string) => {
      if (table === "W26_homepage-image-uploads") {
        return {
          select: uploadsSelectMock,
        };
      }
      if (table === "W26_sites-pa") {
        return {
          select: siteSelectMock,
        };
      }
      throw new Error(`Unexpected table: ${table}`);
    });

    (getSignedUrl as jest.Mock).mockResolvedValueOnce(
      "https://signed-url.example.com/tree.jpg"
    );

    const response = await GET(new Request("http://localhost"), makeParams("207"));
    const body = await response.json();

    expect(response.status).toBe(200);
    expect(body.items).toHaveLength(1);
    expect(body.items[0]).toEqual({
      id: 14,
      site_id: 207,
      site_name: "Riverlot 56 (NA)",
      date: "2026-03-17",
      photographer: "Vishal Sivakumar",
      caption: "Riverlot56 Visit with Frank Potter!",
      identifier: "CMPUT401W26 Visit",
      filename: "tree-A1B2C3D4.jpg",
      file_size_bytes: 111111,
      storage_key: "homepage-image-uploads/207/user-1/tree-A1B2C3D4.jpg",
      imageUrl: "https://signed-url.example.com/tree.jpg",
    });
  });

  it("filters out items where signed URL generation fails", async () => {
    mockGetUser.mockResolvedValue({
      data: { user: { id: "user-1" } },
      error: null,
    });

    const mockUploads = [
      {
        id: 1,
        site_id: 207,
        user_id: "user-1",
        date: "2026-03-17",
        photographer: "Vishal",
        identifier: "Good Image",
        caption: "Works fine",
        storage_key: "homepage-image-uploads/207/user-1/good.jpg",
        filename: "good.jpg",
        content_type: "image/jpeg",
        file_size_bytes: 111111,
      },
      {
        id: 2,
        site_id: 207,
        user_id: "user-1",
        date: "2026-03-17",
        photographer: "Vishal",
        identifier: "Bad Image",
        caption: "S3 fails",
        storage_key: "homepage-image-uploads/207/user-1/bad.jpg",
        filename: "bad.jpg",
        content_type: "image/jpeg",
        file_size_bytes: 222222,
      },
    ];

    const uploadsOrderMock = jest.fn().mockResolvedValue({
      data: mockUploads,
      error: null,
    });

    const uploadsEqMock = jest.fn().mockReturnValue({
      order: uploadsOrderMock,
    });

    const uploadsSelectMock = jest.fn().mockReturnValue({
      eq: uploadsEqMock,
    });

    const siteSingleMock = jest.fn().mockResolvedValue({
      data: { namesite: "Riverlot 56 (NA)" },
      error: null,
    });

    const siteEqMock = jest.fn().mockReturnValue({
      single: siteSingleMock,
    });

    const siteSelectMock = jest.fn().mockReturnValue({
      eq: siteEqMock,
    });

    mockFrom.mockImplementation((table: string) => {
      if (table === "W26_homepage-image-uploads") {
        return {
          select: uploadsSelectMock,
        };
      }
      if (table === "W26_sites-pa") {
        return {
          select: siteSelectMock,
        };
      }
      throw new Error(`Unexpected table: ${table}`);
    });

    (getSignedUrl as jest.Mock)
      .mockResolvedValueOnce("https://signed-url.example.com/good.jpg")
      .mockRejectedValueOnce(new Error("S3 failed"));

    const response = await GET(new Request("http://localhost"), makeParams("207"));
    const body = await response.json();

    expect(response.status).toBe(200);
    expect(body.items).toHaveLength(1);
    expect(body.items[0]).toEqual({
      id: 1,
      site_id: 207,
      site_name: "Riverlot 56 (NA)",
      date: "2026-03-17",
      photographer: "Vishal",
      caption: "Works fine",
      identifier: "Good Image",
      filename: "good.jpg",
      file_size_bytes: 111111,
      storage_key: "homepage-image-uploads/207/user-1/good.jpg",
      imageUrl: "https://signed-url.example.com/good.jpg",
    });
  });

  it("returns site_name as null when site lookup returns no row", async () => {
    mockGetUser.mockResolvedValue({
      data: { user: { id: "user-1" } },
      error: null,
    });

    const mockUpload = {
      id: 14,
      site_id: 207,
      user_id: "user-1",
      date: "2026-03-17",
      photographer: "Vishal Sivakumar",
      identifier: "CMPUT401W26 Visit",
      caption: "Riverlot56 Visit with Frank Potter!",
      storage_key: "homepage-image-uploads/207/user-1/tree-A1B2C3D4.jpg",
      filename: "tree-A1B2C3D4.jpg",
      content_type: "image/jpeg",
      file_size_bytes: 111111,
    };

    const uploadsOrderMock = jest.fn().mockResolvedValue({
      data: [mockUpload],
      error: null,
    });

    const uploadsEqMock = jest.fn().mockReturnValue({
      order: uploadsOrderMock,
    });

    const uploadsSelectMock = jest.fn().mockReturnValue({
      eq: uploadsEqMock,
    });

    const siteSingleMock = jest.fn().mockResolvedValue({
      data: null,
      error: null,
    });

    const siteEqMock = jest.fn().mockReturnValue({
      single: siteSingleMock,
    });

    const siteSelectMock = jest.fn().mockReturnValue({
      eq: siteEqMock,
    });

    mockFrom.mockImplementation((table: string) => {
      if (table === "W26_homepage-image-uploads") {
        return {
          select: uploadsSelectMock,
        };
      }
      if (table === "W26_sites-pa") {
        return {
          select: siteSelectMock,
        };
      }
      throw new Error(`Unexpected table: ${table}`);
    });

    (getSignedUrl as jest.Mock).mockResolvedValueOnce(
      "https://signed-url.example.com/tree.jpg"
    );

    const response = await GET(new Request("http://localhost"), makeParams("207"));
    const body = await response.json();

    expect(response.status).toBe(200);
    expect(body.items[0].site_name).toBeNull();
  });

  it("returns 500 on unexpected auth exception", async () => {
    mockGetUser.mockRejectedValue(new Error("Unexpected auth crash"));

    const response = await GET(new Request("http://localhost"), makeParams("207"));
    const body = await response.json();

    expect(response.status).toBe(500);
    expect(body).toEqual({ error: "Failed to load images" });
  });
});