// Generated by ChatGPT

jest.mock("next/server", () => ({
    NextResponse: {
      json: jest.fn((body, init) => ({
        status: init?.status ?? 200,
        json: async () => body,
      })),
    },
  }));
  
import { GET } from "@/app/api/homepage-images/route";
import { createClient } from "@/utils/supabase/server";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

jest.mock("@/utils/supabase/server", () => ({
    createClient: jest.fn(),
}));

jest.mock("@aws-sdk/client-s3", () => ({
    S3Client: jest.fn().mockImplementation(() => ({})),
    GetObjectCommand: jest.fn().mockImplementation((input) => ({ input })),
}));

jest.mock("@aws-sdk/s3-request-presigner", () => ({
    getSignedUrl: jest.fn(),
}));

describe("GET /api/homepage-images", () => {
    const mockGetUser = jest.fn();
    const mockFrom = jest.fn();

    beforeEach(() => {
        jest.clearAllMocks();

        (createClient as jest.Mock).mockResolvedValue({
        auth: { getUser: mockGetUser },
        from: mockFrom,
        });
    });

    it("returns 401 when user is not authenticated", async () => {
        mockGetUser.mockResolvedValue({ data: { user: null }, error: null });

        const response = await GET();
        const body = await response.json();

        expect(response.status).toBe(401);
        expect(body).toEqual({ error: "Unauthorized" });
    });

    it("returns 401 when auth errors", async () => {
        mockGetUser.mockResolvedValue({ data: { user: null }, error: { message: "Auth failed" } });

        const response = await GET();
        const body = await response.json();

        expect(response.status).toBe(401);
        expect(body).toEqual({ error: "Unauthorized" });
    });

    it("returns 403 when user is not admin", async () => {
        mockGetUser.mockResolvedValue({
        data: { user: { id: "user-1", user_metadata: { role: "user" } } },
        error: null,
        });

        const response = await GET();
        const body = await response.json();

        expect(response.status).toBe(403);
        expect(body).toEqual({ error: "Forbidden" });
    });

    it("returns 500 when uploads query fails", async () => {
        mockGetUser.mockResolvedValue({
        data: { user: { id: "admin-1", user_metadata: { role: "admin" } } },
        error: null,
        });

        mockFrom.mockReturnValue({
        select: jest.fn().mockReturnThis(),
        order: jest.fn().mockResolvedValue({ data: null, error: { message: "DB error" } }),
        });

        const response = await GET();
        const body = await response.json();

        expect(response.status).toBe(500);
        expect(body).toEqual({ error: "DB error" });
    });

    it("returns empty items when no uploads exist", async () => {
        mockGetUser.mockResolvedValue({
        data: { user: { id: "admin-1", user_metadata: { role: "admin" } } },
        error: null,
        });

        mockFrom.mockImplementation((table: string) => {
        if (table === "W26_homepage-image-uploads") {
            return {
            select: jest.fn().mockReturnThis(),
            order: jest.fn().mockResolvedValue({ data: [], error: null }),
            };
        }
        if (table === "W26_sites-pa") {
            return {
            select: jest.fn().mockReturnThis(),
            in: jest.fn().mockResolvedValue({ data: [], error: null }),
            };
        }
        });

        const response = await GET();
        const body = await response.json();

        expect(response.status).toBe(200);
        expect(body).toEqual({ items: [] });
    });

    it("returns items with signed URLs and correct fields", async () => {
        mockGetUser.mockResolvedValue({
        data: { user: { id: "admin-1", user_metadata: { role: "admin" } } },
        error: null,
        });

        const mockUpload = {
            id: 14,
            site_id: 207,
            user_id: "user-1",
            date: "2026-03-17",
            photographer: "Vishal Sivakumar",
            identifier: "CMPUT401W26 Visit",
            description: "Riverlot56 Visit with Frank Potter!",
            storage_key: "homepage-image-uploads/207/user-1/tree-A1B2C3D4.jpg",
            filename: "tree-A1B2C3D4.jpg",
            content_type: "image/jpeg",
            file_size_bytes: 111111,
        };

        mockFrom.mockImplementation((table: string) => {
        if (table === "W26_homepage-image-uploads") {
            return {
            select: jest.fn().mockReturnThis(),
            order: jest.fn().mockResolvedValue({ data: [mockUpload], error: null }),
            };
        }
        if (table === "W26_sites-pa") {
            return {
            select: jest.fn().mockReturnThis(),
            in: jest.fn().mockResolvedValue({ data: [{ id: 207, namesite: "Riverlot 56 (NA)" }], error: null }),
            };
        }
        });

        (getSignedUrl as jest.Mock).mockResolvedValueOnce("https://signed-url.example.com/tree.jpg");

        const response = await GET();
        const body = await response.json();

        expect(response.status).toBe(200);
        expect(body.items).toHaveLength(1);
        expect(body.items[0]).toEqual({
            id: 14,
            site_id: 207,
            site_name: "Riverlot 56 (NA)",
            date: "2026-03-17",
            photographer: "Vishal Sivakumar",
            caption: "CMPUT401W26 Visit",
            description: "Riverlot56 Visit with Frank Potter!",
            filename: "tree-A1B2C3D4.jpg",
            file_size_bytes: 111111,
            storage_key: "homepage-image-uploads/207/user-1/tree-A1B2C3D4.jpg",
            imageUrl: "https://signed-url.example.com/tree.jpg",
        });
    });

    it("filters out items where signed URL generation fails", async () => {
        mockGetUser.mockResolvedValue({
        data: { user: { id: "admin-1", user_metadata: { role: "admin" } } },
        error: null,
        });

        const mockUploads = [
        {
            id: 1,
            site_id: 207,
            user_id: "user-1",
            date: "2026-03-17",
            photographer: "Vishal",
            identifier: "Good Image",
            description: "Works fine",
            storage_key: "homepage-image-uploads/207/user-1/good.jpg",
            filename: "good.jpg",
            content_type: "image/jpeg",
            file_size_bytes: 111111,
        },
        {
            id: 2,
            site_id: 207,
            user_id: "user-1",
            date: "2026-03-17",
            photographer: "Vishal",
            identifier: "Bad Image",
            description: "S3 fails",
            storage_key: "homepage-image-uploads/207/user-1/bad.jpg",
            filename: "bad.jpg",
            content_type: "image/jpeg",
            file_size_bytes: 222222,
        },
        ];

        mockFrom.mockImplementation((table: string) => {
        if (table === "W26_homepage-image-uploads") {
            return {
            select: jest.fn().mockReturnThis(),
            order: jest.fn().mockResolvedValue({ data: mockUploads, error: null }),
            };
        }
        if (table === "W26_sites-pa") {
            return {
            select: jest.fn().mockReturnThis(),
            in: jest.fn().mockResolvedValue({ data: [{ id: 207, namesite: "Riverlot 56 (NA)" }], error: null }),
            };
        }
        });

        (getSignedUrl as jest.Mock)
        .mockResolvedValueOnce("https://signed-url.example.com/good.jpg")
        .mockRejectedValueOnce(new Error("S3 failed"));

        const response = await GET();
        const body = await response.json();

        expect(response.status).toBe(200);
        expect(body.items).toHaveLength(1);
        expect(body.items[0].caption).toBe("Good Image");
    });

    it("returns 500 on unexpected auth exception", async () => {
        mockGetUser.mockRejectedValue(new Error("Unexpected auth crash"));

        const response = await GET();
        const body = await response.json();

        expect(response.status).toBe(500);
        expect(body).toEqual({ error: "Failed to load images" });
    });
});