// Generated by ChatGPT

jest.mock("next/server", () => ({
    NextResponse: {
      json: jest.fn((body, init) => ({
        status: init?.status ?? 200,
        json: async () => body,
      })),
    },
  }));
  
jest.mock("crypto", () => ({
    randomUUID: jest.fn(() => "mock-uuid-123"),
}));

import { POST } from "@/app/api/s3/presign-homepage-images/route";
import { createClient } from "@/utils/supabase/server";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import crypto from "crypto";

jest.mock("@/utils/supabase/server", () => ({
    createClient: jest.fn(),
}));

jest.mock("@aws-sdk/client-s3", () => ({
    S3Client: jest.fn().mockImplementation(() => ({})),
    PutObjectCommand: jest.fn().mockImplementation((input) => ({ input })),
}));

jest.mock("@aws-sdk/s3-request-presigner", () => ({
    getSignedUrl: jest.fn(),
}));

describe("POST /api/s3/presign-homepage-images", () => {
    const mockGetUser = jest.fn();

    beforeEach(() => {
        jest.clearAllMocks();

        (createClient as jest.Mock).mockResolvedValue({
        auth: { getUser: mockGetUser },
        });

        (crypto.randomUUID as jest.Mock).mockReturnValue("mock-uuid-123");
    });

    it("returns 401 when user is not authenticated", async () => {
        mockGetUser.mockResolvedValue({ data: { user: null }, error: null });

        const request = new Request("http://localhost:3000/api/s3/presign-homepage-images", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ filename: "tree.jpg", contentType: "image/jpeg", fileSize: 1000, siteId: 207 }),
        });

        const response = await POST(request);
        const body = await response.json();

        expect(response.status).toBe(401);
        expect(body).toEqual({ error: "Unauthorized" });
    });

    it("returns 401 when auth errors", async () => {
        mockGetUser.mockResolvedValue({ data: { user: null }, error: { message: "Auth failed" } });

        const request = new Request("http://localhost:3000/api/s3/presign-homepage-images", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ filename: "tree.jpg", contentType: "image/jpeg", fileSize: 1000, siteId: 207 }),
        });

        const response = await POST(request);
        const body = await response.json();

        expect(response.status).toBe(401);
        expect(body).toEqual({ error: "Unauthorized" });
    });

    it("returns 400 when filename is missing", async () => {
        mockGetUser.mockResolvedValue({ data: { user: { id: "user-1" } }, error: null });

        const request = new Request("http://localhost:3000/api/s3/presign-homepage-images", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ filename: "", contentType: "image/jpeg", fileSize: 1000, siteId: 207 }),
        });

        const response = await POST(request);
        const body = await response.json();

        expect(response.status).toBe(400);
        expect(body).toEqual({ error: "Invalid file data" });
    });

    it("returns 400 when contentType is missing", async () => {
        mockGetUser.mockResolvedValue({ data: { user: { id: "user-1" } }, error: null });

        const request = new Request("http://localhost:3000/api/s3/presign-homepage-images", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ filename: "tree.jpg", contentType: "", fileSize: 1000, siteId: 207 }),
        });

        const response = await POST(request);
        const body = await response.json();

        expect(response.status).toBe(400);
        expect(body).toEqual({ error: "Invalid file data" });
    });

    it("returns 400 when siteId is missing", async () => {
        mockGetUser.mockResolvedValue({ data: { user: { id: "user-1" } }, error: null });

        const request = new Request("http://localhost:3000/api/s3/presign-homepage-images", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ filename: "tree.jpg", contentType: "image/jpeg", fileSize: 1000, siteId: null }),
        });

        const response = await POST(request);
        const body = await response.json();

        expect(response.status).toBe(400);
        expect(body).toEqual({ error: "Missing siteId" });
    });

    it("returns 400 for unsupported file type", async () => {
        mockGetUser.mockResolvedValue({ data: { user: { id: "user-1" } }, error: null });

        const request = new Request("http://localhost:3000/api/s3/presign-homepage-images", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ filename: "tree.gif", contentType: "image/gif", fileSize: 1000, siteId: 207 }),
        });

        const response = await POST(request);
        const body = await response.json();

        expect(response.status).toBe(400);
        expect(body).toEqual({ error: "Unsupported file type" });
    });

    it("returns 400 when file is too large", async () => {
        mockGetUser.mockResolvedValue({ data: { user: { id: "user-1" } }, error: null });

        const request = new Request("http://localhost:3000/api/s3/presign-homepage-images", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ filename: "tree.jpg", contentType: "image/jpeg", fileSize: 11 * 1024 * 1024, siteId: 207 }),
        });

        const response = await POST(request);
        const body = await response.json();

        expect(response.status).toBe(400);
        expect(body).toEqual({ error: "File too large" });
    });

    it("returns upload url and key for jpeg", async () => {
        mockGetUser.mockResolvedValue({ data: { user: { id: "user-1" } }, error: null });
        (getSignedUrl as jest.Mock).mockResolvedValueOnce("https://signed-upload.example.com/jpeg");

        const request = new Request("http://localhost:3000/api/s3/presign-homepage-images", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ filename: "tree.jpg", contentType: "image/jpeg", fileSize: 1000, siteId: 207 }),
        });

        const response = await POST(request);
        const body = await response.json();

        expect(crypto.randomUUID).toHaveBeenCalled();
        expect(getSignedUrl).toHaveBeenCalled();
        expect(response.status).toBe(200);
        expect(body).toEqual({
        uploadUrl: "https://signed-upload.example.com/jpeg",
        key: "homepage-image-uploads/207/user-1/tree-mock-uuid-123.jpg",
        });
    });

    it("returns upload url and key for png", async () => {
        mockGetUser.mockResolvedValue({ data: { user: { id: "user-1" } }, error: null });
        (getSignedUrl as jest.Mock).mockResolvedValueOnce("https://signed-upload.example.com/png");

        const request = new Request("http://localhost:3000/api/s3/presign-homepage-images", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ filename: "tree.png", contentType: "image/png", fileSize: 1000, siteId: 208 }),
        });

        const response = await POST(request);
        const body = await response.json();

        expect(response.status).toBe(200);
        expect(body).toEqual({
        uploadUrl: "https://signed-upload.example.com/png",
        key: "homepage-image-uploads/208/user-1/tree-mock-uuid-123.png",
        });
    });

    it("returns upload url and key for webp", async () => {
        mockGetUser.mockResolvedValue({ data: { user: { id: "user-1" } }, error: null });
        (getSignedUrl as jest.Mock).mockResolvedValueOnce("https://signed-upload.example.com/webp");

        const request = new Request("http://localhost:3000/api/s3/presign-homepage-images", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ filename: "tree.webp", contentType: "image/webp", fileSize: 1000, siteId: 209 }),
        });

        const response = await POST(request);
        const body = await response.json();

        expect(response.status).toBe(200);
        expect(body).toEqual({
        uploadUrl: "https://signed-upload.example.com/webp",
        key: "homepage-image-uploads/209/user-1/tree-mock-uuid-123.webp",
        });
    });

    it("returns 500 when request.json throws", async () => {
        mockGetUser.mockResolvedValue({ data: { user: { id: "user-1" } }, error: null });

        const badRequest = {
        json: jest.fn().mockRejectedValue(new Error("Invalid JSON")),
        } as unknown as Request;

        const response = await POST(badRequest);
        const body = await response.json();

        expect(response.status).toBe(500);
        expect(body).toEqual({ error: "Failed to generate upload URL" });
    });

    it("returns 500 when signed url generation fails", async () => {
        mockGetUser.mockResolvedValue({ data: { user: { id: "user-1" } }, error: null });
        (getSignedUrl as jest.Mock).mockRejectedValueOnce(new Error("S3 failed"));

        const request = new Request("http://localhost:3000/api/s3/presign-homepage-images", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ filename: "tree.jpg", contentType: "image/jpeg", fileSize: 1000, siteId: 207 }),
        });

        const response = await POST(request);
        const body = await response.json();

        expect(response.status).toBe(500);
        expect(body).toEqual({ error: "Failed to generate upload URL" });
    });

    it("returns 500 on unexpected auth exception", async () => {
        mockGetUser.mockRejectedValue(new Error("Unexpected auth crash"));

        const request = new Request("http://localhost:3000/api/s3/presign-homepage-images", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ filename: "tree.jpg", contentType: "image/jpeg", fileSize: 1000, siteId: 207 }),
        });

        const response = await POST(request);
        const body = await response.json();

        expect(response.status).toBe(500);
        expect(body).toEqual({ error: "Failed to generate upload URL" });
    });
});