// Generated by ChatGPT

jest.mock("next/server", () => ({
  NextResponse: {
    json: jest.fn((body, init) => ({
      status: init?.status ?? 200,
      json: async () => body,
    })),
  },
}));

import { POST } from "@/app/api/s3/presign-homepage-images/route";
import { createClient } from "@/utils/supabase/server";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { generateFilename } from "@/utils/media/generateFilename";

jest.mock("@/utils/supabase/server", () => ({
  createClient: jest.fn(),
}));

jest.mock("@aws-sdk/client-s3", () => ({
  S3Client: jest.fn().mockImplementation(() => ({})),
  PutObjectCommand: jest.fn().mockImplementation((input) => ({ input })),
}));

jest.mock("@aws-sdk/s3-request-presigner", () => ({
  getSignedUrl: jest.fn(),
}));

jest.mock("@/utils/media/generateFilename", () => ({
  generateFilename: jest.fn(),
}));

describe("POST /api/s3/presign-homepage-images", () => {
  const mockGetUser = jest.fn();

  const validBody = {
    contentType: "image/jpeg",
    fileSize: 1000,
    siteId: 207,
    siteName: "Riverlot 56",
    date: "2026-03-21",
    photographer: "Raiyana Rahman",
    identifier: "Broken Tree",
  };

  beforeEach(() => {
    jest.clearAllMocks();

    (createClient as jest.Mock).mockResolvedValue({
      auth: {
        getUser: mockGetUser,
      },
    });

    (generateFilename as jest.Mock).mockReturnValue(
      "Riverlot56-2026-03-21-RaiyanaRahman-BrokenTree-generated.jpg"
    );
  });

  it("returns 401 when user is not authenticated", async () => {
    mockGetUser.mockResolvedValue({
      data: { user: null },
      error: null,
    });

    const request = new Request("http://localhost:3000/api/s3/presign-homepage-images", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(validBody),
    });

    const response = await POST(request);
    const body = await response.json();

    expect(response.status).toBe(401);
    expect(body).toEqual({ error: "Unauthorized" });
  });

  it("returns 401 when auth errors", async () => {
    mockGetUser.mockResolvedValue({
      data: { user: null },
      error: { message: "Auth failed" },
    });

    const request = new Request("http://localhost:3000/api/s3/presign-homepage-images", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(validBody),
    });

    const response = await POST(request);
    const body = await response.json();

    expect(response.status).toBe(401);
    expect(body).toEqual({ error: "Unauthorized" });
  });

  it("returns 400 when contentType is missing", async () => {
    mockGetUser.mockResolvedValue({
      data: { user: { id: "user-1" } },
      error: null,
    });

    const request = new Request("http://localhost:3000/api/s3/presign-homepage-images", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        ...validBody,
        contentType: "",
      }),
    });

    const response = await POST(request);
    const body = await response.json();

    expect(response.status).toBe(400);
    expect(body).toEqual({ error: "Invalid file data" });
  });

  it("returns 400 when siteId is missing", async () => {
    mockGetUser.mockResolvedValue({
      data: { user: { id: "user-1" } },
      error: null,
    });

    const request = new Request("http://localhost:3000/api/s3/presign-homepage-images", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        ...validBody,
        siteId: null,
      }),
    });

    const response = await POST(request);
    const body = await response.json();

    expect(response.status).toBe(400);
    expect(body).toEqual({ error: "Missing siteId" });
  });

  it("returns 400 when metadata is missing", async () => {
    mockGetUser.mockResolvedValue({
      data: { user: { id: "user-1" } },
      error: null,
    });

    const request = new Request("http://localhost:3000/api/s3/presign-homepage-images", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        ...validBody,
        identifier: "",
      }),
    });

    const response = await POST(request);
    const body = await response.json();

    expect(response.status).toBe(400);
    expect(body).toEqual({ error: "Missing metadata" });
  });

  it("returns 400 for unsupported file type", async () => {
    mockGetUser.mockResolvedValue({
      data: { user: { id: "user-1" } },
      error: null,
    });

    const request = new Request("http://localhost:3000/api/s3/presign-homepage-images", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        ...validBody,
        contentType: "image/gif",
      }),
    });

    const response = await POST(request);
    const body = await response.json();

    expect(response.status).toBe(400);
    expect(body).toEqual({ error: "Unsupported file type" });
  });

  it("returns 400 when file is too large", async () => {
    mockGetUser.mockResolvedValue({
      data: { user: { id: "user-1" } },
      error: null,
    });

    const request = new Request("http://localhost:3000/api/s3/presign-homepage-images", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        ...validBody,
        fileSize: 11 * 1024 * 1024,
      }),
    });

    const response = await POST(request);
    const body = await response.json();

    expect(response.status).toBe(400);
    expect(body).toEqual({ error: "File too large" });
  });

  it("returns upload url and key for jpeg", async () => {
    mockGetUser.mockResolvedValue({
      data: {
        user: { id: "user-1" },
      },
      error: null,
    });

    (generateFilename as jest.Mock).mockReturnValueOnce(
      "Riverlot56-2026-03-21-RaiyanaRahman-BrokenTree-generated.jpg"
    );

    (getSignedUrl as jest.Mock).mockResolvedValueOnce(
      "https://signed-upload.example.com/jpeg"
    );

    const request = new Request("http://localhost:3000/api/s3/presign-homepage-images", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        ...validBody,
        contentType: "image/jpeg",
      }),
    });

    const response = await POST(request);
    const body = await response.json();

    expect(generateFilename).toHaveBeenCalledWith({
      siteName: "Riverlot 56",
      date: "2026-03-21",
      photographer: "Raiyana Rahman",
      identifier: "Broken Tree",
      extension: "jpg",
    });

    expect(getSignedUrl).toHaveBeenCalled();
    expect(response.status).toBe(200);
    expect(body).toEqual({
      uploadUrl: "https://signed-upload.example.com/jpeg",
      key: "homepage-image-uploads/207/user-1/Riverlot56-2026-03-21-RaiyanaRahman-BrokenTree-generated.jpg",
    });
  });

  it("returns upload url and key for png", async () => {
    mockGetUser.mockResolvedValue({
      data: {
        user: { id: "user-1" },
      },
      error: null,
    });

    (generateFilename as jest.Mock).mockReturnValueOnce(
      "Riverlot56-2026-03-21-RaiyanaRahman-BrokenTree-generated.png"
    );

    (getSignedUrl as jest.Mock).mockResolvedValueOnce(
      "https://signed-upload.example.com/png"
    );

    const request = new Request("http://localhost:3000/api/s3/presign-homepage-images", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        ...validBody,
        contentType: "image/png",
      }),
    });

    const response = await POST(request);
    const body = await response.json();

    expect(generateFilename).toHaveBeenCalledWith({
      siteName: "Riverlot 56",
      date: "2026-03-21",
      photographer: "Raiyana Rahman",
      identifier: "Broken Tree",
      extension: "png",
    });

    expect(response.status).toBe(200);
    expect(body).toEqual({
      uploadUrl: "https://signed-upload.example.com/png",
      key: "homepage-image-uploads/207/user-1/Riverlot56-2026-03-21-RaiyanaRahman-BrokenTree-generated.png",
    });
  });

  it("returns upload url and key for webp", async () => {
    mockGetUser.mockResolvedValue({
      data: {
        user: { id: "user-1" },
      },
      error: null,
    });

    (generateFilename as jest.Mock).mockReturnValueOnce(
      "Riverlot56-2026-03-21-RaiyanaRahman-BrokenTree-generated.webp"
    );

    (getSignedUrl as jest.Mock).mockResolvedValueOnce(
      "https://signed-upload.example.com/webp"
    );

    const request = new Request("http://localhost:3000/api/s3/presign-homepage-images", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        ...validBody,
        contentType: "image/webp",
      }),
    });

    const response = await POST(request);
    const body = await response.json();

    expect(generateFilename).toHaveBeenCalledWith({
      siteName: "Riverlot 56",
      date: "2026-03-21",
      photographer: "Raiyana Rahman",
      identifier: "Broken Tree",
      extension: "webp",
    });

    expect(response.status).toBe(200);
    expect(body).toEqual({
      uploadUrl: "https://signed-upload.example.com/webp",
      key: "homepage-image-uploads/207/user-1/Riverlot56-2026-03-21-RaiyanaRahman-BrokenTree-generated.webp",
    });
  });

  it("returns 500 when request.json throws", async () => {
    mockGetUser.mockResolvedValue({
      data: {
        user: { id: "user-1" },
      },
      error: null,
    });

    const badRequest = {
      json: jest.fn().mockRejectedValue(new Error("Invalid JSON")),
    } as unknown as Request;

    const response = await POST(badRequest);
    const body = await response.json();

    expect(response.status).toBe(500);
    expect(body).toEqual({ error: "Failed to generate upload URL" });
  });

  it("returns 500 when signed url generation fails", async () => {
    mockGetUser.mockResolvedValue({
      data: {
        user: { id: "user-1" },
      },
      error: null,
    });

    (getSignedUrl as jest.Mock).mockRejectedValueOnce(new Error("S3 failed"));

    const request = new Request("http://localhost:3000/api/s3/presign-homepage-images", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(validBody),
    });

    const response = await POST(request);
    const body = await response.json();

    expect(response.status).toBe(500);
    expect(body).toEqual({ error: "Failed to generate upload URL" });
  });

  it("returns 500 on unexpected auth exception", async () => {
    mockGetUser.mockRejectedValue(new Error("Unexpected auth crash"));

    const request = new Request("http://localhost:3000/api/s3/presign-homepage-images", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(validBody),
    });

    const response = await POST(request);
    const body = await response.json();

    expect(response.status).toBe(500);
    expect(body).toEqual({ error: "Failed to generate upload URL" });
  });
});