//Generated by ChatGPT 

jest.mock("next/server", () => ({
  NextResponse: {
    json: jest.fn((body, init) => ({
      status: init?.status ?? 200,
      json: async () => body,
    })),
  },
}));

import { GET } from "@/app/api/site-images/route";
import { createClient } from "@/utils/supabase/server";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

jest.mock("@/utils/supabase/server", () => ({
  createClient: jest.fn(),
}));

jest.mock("@aws-sdk/client-s3", () => ({
  S3Client: jest.fn().mockImplementation(() => ({})),
  GetObjectCommand: jest.fn().mockImplementation((input) => ({ input })),
}));

jest.mock("@aws-sdk/s3-request-presigner", () => ({
  getSignedUrl: jest.fn(),
}));

describe("GET /api/site-images", () => {
  const mockGetUser = jest.fn();
  const mockFrom = jest.fn();

  beforeEach(() => {
    jest.clearAllMocks();

    (createClient as jest.Mock).mockResolvedValue({
      auth: {
        getUser: mockGetUser,
      },
      from: mockFrom,
    });
  });

  it("returns 401 when user is unauthorized", async () => {
    mockGetUser.mockResolvedValue({
      data: { user: null },
      error: null,
    });

    const request = new Request("http://localhost:3000/api/site-images?siteid=207");
    const response = await GET(request);
    const body = await response.json();

    expect(response.status).toBe(401);
    expect(body).toEqual({ error: "Unauthorized" });
  });

  it("returns 401 when auth errors", async () => {
    mockGetUser.mockResolvedValue({
      data: { user: null },
      error: { message: "Auth failed" },
    });

    const request = new Request("http://localhost:3000/api/site-images?siteid=207");
    const response = await GET(request);
    const body = await response.json();

    expect(response.status).toBe(401);
    expect(body).toEqual({ error: "Unauthorized" });
  });

  it("returns 400 when both siteid and responseid are missing", async () => {
    mockGetUser.mockResolvedValue({
      data: { user: { id: "user-1" } },
      error: null,
    });

    const request = new Request("http://localhost:3000/api/site-images");
    const response = await GET(request);
    const body = await response.json();

    expect(response.status).toBe(400);
    expect(body).toEqual({
      error: "Provide at least one of: siteid, responseid",
    });
  });

  it("returns empty items when no attachments are found", async () => {
    mockGetUser.mockResolvedValue({
      data: { user: { id: "user-1" } },
      error: null,
    });

    const queryBuilder: any = {
      eq: jest.fn().mockReturnThis(),
      then: jest.fn((resolve: any) =>
        resolve({
          data: [],
          error: null,
        })
      ),
    };

    mockFrom.mockReturnValue({
      select: jest.fn().mockReturnValue(queryBuilder),
    });

    const request = new Request("http://localhost:3000/api/site-images?siteid=207");
    const response = await GET(request);
    const body = await response.json();

    expect(response.status).toBe(200);
    expect(queryBuilder.eq).toHaveBeenCalledWith("site_id", 207);
    expect(body).toEqual({ items: [] });
  });

  it("returns items filtered by siteid", async () => {
    mockGetUser.mockResolvedValue({
      data: { user: { id: "user-1" } },
      error: null,
    });

    const attachmentsData = [
      {
        id: 14,
        response_id: 3235,
        question_id: 27,
        storage_key: "inspections/207/3235/27/file1.jpg",
        filename: "file1.jpg",
        content_type: "image/jpeg",
        file_size_bytes: 2433304,
        caption: "Cracked Tree",
        description: "Large crack running up the trunk of a tree.",
        site_id: 207,
      },
    ];

    const queryBuilder: any = {
      eq: jest.fn().mockReturnThis(),
      then: jest.fn((resolve: any) =>
        resolve({
          data: attachmentsData,
          error: null,
        })
      ),
    };

    mockFrom.mockReturnValue({
      select: jest.fn().mockReturnValue(queryBuilder),
    });

    (getSignedUrl as jest.Mock).mockResolvedValueOnce(
      "https://signed-url.example.com/file1.jpg"
    );

    const request = new Request("http://localhost:3000/api/site-images?siteid=207");
    const response = await GET(request);
    const body = await response.json();

    expect(response.status).toBe(200);
    expect(queryBuilder.eq).toHaveBeenCalledWith("site_id", 207);
    expect(body).toEqual({
      items: [
        {
          id: 14,
          response_id: 3235,
          question_id: 27,
          storage_key: "inspections/207/3235/27/file1.jpg",
          filename: "file1.jpg",
          content_type: "image/jpeg",
          file_size_bytes: 2433304,
          caption: "Cracked Tree",
          description: "Large crack running up the trunk of a tree.",
          site_id: 207,
          imageUrl: "https://signed-url.example.com/file1.jpg",
        },
      ],
    });
  });

  it("returns items filtered by responseid", async () => {
    mockGetUser.mockResolvedValue({
      data: { user: { id: "user-1" } },
      error: null,
    });

    const attachmentsData = [
      {
        id: 15,
        response_id: 4001,
        question_id: 29,
        storage_key: "inspections/207/4001/29/file2.png",
        filename: "file2.png",
        content_type: "image/png",
        file_size_bytes: 120000,
        caption: "Trail Damage",
        description: "Visible trail damage",
        site_id: 207,
      },
    ];

    const queryBuilder: any = {
      eq: jest.fn().mockReturnThis(),
      then: jest.fn((resolve: any) =>
        resolve({
          data: attachmentsData,
          error: null,
        })
      ),
    };

    mockFrom.mockReturnValue({
      select: jest.fn().mockReturnValue(queryBuilder),
    });

    (getSignedUrl as jest.Mock).mockResolvedValueOnce(
      "https://signed-url.example.com/file2.png"
    );

    const request = new Request("http://localhost:3000/api/site-images?responseid=4001");
    const response = await GET(request);
    const body = await response.json();

    expect(response.status).toBe(200);
    expect(queryBuilder.eq).toHaveBeenCalledWith("response_id", 4001);
    expect(body.items).toHaveLength(1);
    expect(body.items[0].response_id).toBe(4001);
  });

  it("applies both siteid and responseid filters when both are provided", async () => {
    mockGetUser.mockResolvedValue({
      data: { user: { id: "user-1" } },
      error: null,
    });

    const attachmentsData = [
      {
        id: 16,
        response_id: 3235,
        question_id: 30,
        storage_key: "inspections/207/3235/30/file3.webp",
        filename: "file3.webp",
        content_type: "image/webp",
        file_size_bytes: 99999,
        caption: "Wetland",
        description: "Wetland condition image",
        site_id: 207,
      },
    ];

    const queryBuilder: any = {
      eq: jest.fn().mockReturnThis(),
      then: jest.fn((resolve: any) =>
        resolve({
          data: attachmentsData,
          error: null,
        })
      ),
    };

    mockFrom.mockReturnValue({
      select: jest.fn().mockReturnValue(queryBuilder),
    });

    (getSignedUrl as jest.Mock).mockResolvedValueOnce(
      "https://signed-url.example.com/file3.webp"
    );

    const request = new Request(
      "http://localhost:3000/api/site-images?siteid=207&responseid=3235"
    );
    const response = await GET(request);
    const body = await response.json();

    expect(response.status).toBe(200);
    expect(queryBuilder.eq).toHaveBeenNthCalledWith(1, "site_id", 207);
    expect(queryBuilder.eq).toHaveBeenNthCalledWith(2, "response_id", 3235);
    expect(body.items).toHaveLength(1);
  });

  it("returns 500 when database query fails", async () => {
    mockGetUser.mockResolvedValue({
      data: { user: { id: "user-1" } },
      error: null,
    });

    const queryBuilder: any = {
      eq: jest.fn().mockReturnThis(),
      then: jest.fn((resolve: any) =>
        resolve({
          data: null,
          error: { message: "DB exploded" },
        })
      ),
    };

    mockFrom.mockReturnValue({
      select: jest.fn().mockReturnValue(queryBuilder),
    });

    const request = new Request("http://localhost:3000/api/site-images?siteid=207");
    const response = await GET(request);
    const body = await response.json();

    expect(response.status).toBe(500);
    expect(body).toEqual({ error: "Failed to fetch site images" });
  });

  it("returns 500 when signed URL generation fails", async () => {
    mockGetUser.mockResolvedValue({
      data: { user: { id: "user-1" } },
      error: null,
    });

    const attachmentsData = [
      {
        id: 14,
        response_id: 3235,
        question_id: 27,
        storage_key: "inspections/207/3235/27/file1.jpg",
        filename: "file1.jpg",
        content_type: "image/jpeg",
        file_size_bytes: 2433304,
        caption: "Cracked Tree",
        description: "Large crack running up the trunk of a tree.",
        site_id: 207,
      },
    ];

    const queryBuilder: any = {
      eq: jest.fn().mockReturnThis(),
      then: jest.fn((resolve: any) =>
        resolve({
          data: attachmentsData,
          error: null,
        })
      ),
    };

    mockFrom.mockReturnValue({
      select: jest.fn().mockReturnValue(queryBuilder),
    });

    (getSignedUrl as jest.Mock).mockRejectedValueOnce(new Error("S3 failed"));

    const request = new Request("http://localhost:3000/api/site-images?siteid=207");
    const response = await GET(request);
    const body = await response.json();

    expect(response.status).toBe(500);
    expect(body).toEqual({ error: "Failed to fetch site images" });
  });

  it("returns 500 on unexpected exception", async () => {
    mockGetUser.mockRejectedValue(new Error("Unexpected auth crash"));

    const request = new Request("http://localhost:3000/api/site-images?siteid=207");
    const response = await GET(request);
    const body = await response.json();

    expect(response.status).toBe(500);
    expect(body).toEqual({ error: "Failed to fetch site images" });
  });
});