//Generated by ChatGpt

// jest.mock("next/server", () => ({
//   NextResponse: {
//     json: jest.fn((body, init) => ({
//       status: init?.status ?? 200,
//       json: async () => body,
//     })),
//   },
// }));

// import { GET } from "@/app/api/sites/[siteId]/gallery/route";
// import { createClient } from "@/utils/supabase/server";
// import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

// jest.mock("@/utils/supabase/server", () => ({
//   createClient: jest.fn(),
// }));

// jest.mock("@aws-sdk/client-s3", () => ({
//   S3Client: jest.fn().mockImplementation(() => ({})),
//   GetObjectCommand: jest.fn().mockImplementation((input) => ({ input })),
// }));

// jest.mock("@aws-sdk/s3-request-presigner", () => ({
//   getSignedUrl: jest.fn(),
// }));

// describe("GET /api/sites/[siteId]/gallery", () => {
//   const mockGetUser = jest.fn();
//   const mockFrom = jest.fn();

//   beforeEach(() => {
//     jest.clearAllMocks();

//     (createClient as jest.Mock).mockResolvedValue({
//       auth: {
//         getUser: mockGetUser,
//       },
//       from: mockFrom,
//     });
//   });

//   it("returns 400 for invalid site id", async () => {
//     const response = await GET({} as Request, {
//       params: Promise.resolve({ siteId: "abc" }),
//     });

//     const body = await response.json();

//     expect(response.status).toBe(400);
//     expect(body).toEqual({ error: "Invalid site id" });
//   });

//   it("returns 400 when site id is missing", async () => {
//     const response = await GET({} as Request, {
//       params: Promise.resolve({ siteId: "" }),
//     });

//     const body = await response.json();

//     expect(response.status).toBe(400);
//     expect(body).toEqual({ error: "Invalid site id" });
//   });

//   it("returns 401 when user is unauthorized", async () => {
//     mockGetUser.mockResolvedValue({
//       data: { user: null },
//       error: null,
//     });

//     const response = await GET({} as Request, {
//       params: Promise.resolve({ siteId: "207" }),
//     });

//     const body = await response.json();

//     expect(response.status).toBe(401);
//     expect(body).toEqual({ error: "Unauthorized" });
//   });

//   it("returns 401 when auth errors", async () => {
//     mockGetUser.mockResolvedValue({
//       data: { user: null },
//       error: { message: "Auth failed" },
//     });

//     const response = await GET({} as Request, {
//       params: Promise.resolve({ siteId: "207" }),
//     });

//     const body = await response.json();

//     expect(response.status).toBe(401);
//     expect(body).toEqual({ error: "Unauthorized" });
//   });

//   it("returns gallery items successfully", async () => {
//     mockGetUser.mockResolvedValue({
//       data: {
//         user: {
//           id: "user-1",
//           user_metadata: { role: "steward" },
//         },
//       },
//       error: null,
//     });

//     const attachmentsData = [
//       {
//         id: "14",
//         caption: "Cracked Tree",
//         description: "Large crack running up the trunk of a tree.",
//         content_type: "image/jpeg",
//         storage_key: "inspections/207/3226/27/file1.jpg",
//         file_size_bytes: 2433304,
//         filename: "RiverLot56_01-31-2026_ZoeP_CrackedTree.jpg",
//         site_id: "207",
//       },
//       {
//         id: "15",
//         caption: "Trail Damage",
//         description: "Visible ATV tracks.",
//         content_type: "image/png",
//         storage_key: "inspections/207/3227/28/file2.png",
//         file_size_bytes: 123456,
//         filename: "TrailDamage.png",
//         site_id: "207",
//       },
//     ];

//     const attachmentsOrderMock = jest.fn().mockResolvedValue({
//       data: attachmentsData,
//       error: null,
//     });

//     const attachmentsInMock = jest.fn().mockReturnValue({
//       order: attachmentsOrderMock,
//     });

//     const attachmentsEqMock = jest.fn().mockReturnValue({
//       in: attachmentsInMock,
//     });

//     const attachmentsSelectMock = jest.fn().mockReturnValue({
//       eq: attachmentsEqMock,
//     });

//     const siteSingleMock = jest.fn().mockResolvedValue({
//       data: { namesite: "Riverlot 56 (NA)" },
//       error: null,
//     });

//     const siteEqMock = jest.fn().mockReturnValue({
//       single: siteSingleMock,
//     });

//     const siteSelectMock = jest.fn().mockReturnValue({
//       eq: siteEqMock,
//     });

//     mockFrom.mockImplementation((table: string) => {
//       if (table === "W26_attachments") {
//         return {
//           select: attachmentsSelectMock,
//         };
//       }

//       if (table === "W26_sites-pa") {
//         return {
//           select: siteSelectMock,
//         };
//       }

//       throw new Error(`Unexpected table: ${table}`);
//     });

//     (getSignedUrl as jest.Mock)
//       .mockResolvedValueOnce("https://signed-url.example.com/file1.jpg")
//       .mockResolvedValueOnce("https://signed-url.example.com/file2.png");

//     const response = await GET({} as Request, {
//       params: Promise.resolve({ siteId: "207" }),
//     });

//     const body = await response.json();

//     expect(response.status).toBe(200);

//     expect(mockFrom).toHaveBeenCalledWith("W26_attachments");
//     expect(mockFrom).toHaveBeenCalledWith("W26_sites-pa");

//     expect(attachmentsEqMock).toHaveBeenCalledWith("site_id", 207);
//     expect(attachmentsInMock).toHaveBeenCalledWith("content_type", [
//       "image/jpeg",
//       "image/png",
//       "image/webp",
//     ]);

//     expect(siteEqMock).toHaveBeenCalledWith("id", "207");

//     expect(body).toEqual({
//       items: [
//         {
//           id: "14",
//           caption: "Cracked Tree",
//           description: "Large crack running up the trunk of a tree.",
//           filename: "RiverLot56_01-31-2026_ZoeP_CrackedTree.jpg",
//           file_size_bytes: 2433304,
//           site_name: "Riverlot 56 (NA)",
//           imageUrl: "https://signed-url.example.com/file1.jpg",
//         },
//         {
//           id: "15",
//           caption: "Trail Damage",
//           description: "Visible ATV tracks.",
//           filename: "TrailDamage.png",
//           file_size_bytes: 123456,
//           site_name: "Riverlot 56 (NA)",
//           imageUrl: "https://signed-url.example.com/file2.png",
//         },
//       ],
//     });
//   });

//   it("filters out items whose signed URL generation fails", async () => {
//     mockGetUser.mockResolvedValue({
//       data: {
//         user: {
//           id: "user-1",
//         },
//       },
//       error: null,
//     });

//     const attachmentsData = [
//       {
//         id: "14",
//         caption: "Cracked Tree",
//         description: "desc1",
//         content_type: "image/jpeg",
//         storage_key: "inspections/207/3226/27/file1.jpg",
//         file_size_bytes: 2433304,
//         filename: "file1.jpg",
//         site_id: "207",
//       },
//       {
//         id: "15",
//         caption: "Trail Damage",
//         description: "desc2",
//         content_type: "image/png",
//         storage_key: "inspections/207/3227/28/file2.png",
//         file_size_bytes: 123456,
//         filename: "file2.png",
//         site_id: "207",
//       },
//     ];

//     const attachmentsOrderMock = jest.fn().mockResolvedValue({
//       data: attachmentsData,
//       error: null,
//     });

//     const attachmentsInMock = jest.fn().mockReturnValue({
//       order: attachmentsOrderMock,
//     });

//     const attachmentsEqMock = jest.fn().mockReturnValue({
//       in: attachmentsInMock,
//     });

//     const attachmentsSelectMock = jest.fn().mockReturnValue({
//       eq: attachmentsEqMock,
//     });

//     const siteSingleMock = jest.fn().mockResolvedValue({
//       data: { namesite: "Riverlot 56 (NA)" },
//       error: null,
//     });

//     const siteEqMock = jest.fn().mockReturnValue({
//       single: siteSingleMock,
//     });

//     const siteSelectMock = jest.fn().mockReturnValue({
//       eq: siteEqMock,
//     });

//     mockFrom.mockImplementation((table: string) => {
//       if (table === "W26_attachments") {
//         return {
//           select: attachmentsSelectMock,
//         };
//       }

//       if (table === "W26_sites-pa") {
//         return {
//           select: siteSelectMock,
//         };
//       }

//       throw new Error(`Unexpected table: ${table}`);
//     });

//     (getSignedUrl as jest.Mock)
//       .mockResolvedValueOnce("https://signed-url.example.com/file1.jpg")
//       .mockRejectedValueOnce(new Error("S3 failed"));

//     const response = await GET({} as Request, {
//       params: Promise.resolve({ siteId: "207" }),
//     });

//     const body = await response.json();

//     expect(response.status).toBe(200);
//     expect(body.items).toHaveLength(1);
//     expect(body.items[0]).toEqual({
//       id: "14",
//       caption: "Cracked Tree",
//       description: "desc1",
//       filename: "file1.jpg",
//       file_size_bytes: 2433304,
//       site_name: "Riverlot 56 (NA)",
//       imageUrl: "https://signed-url.example.com/file1.jpg",
//     });
//   });

//   it("returns 500 when attachments query fails", async () => {
//     mockGetUser.mockResolvedValue({
//       data: {
//         user: {
//           id: "user-1",
//         },
//       },
//       error: null,
//     });

//     const attachmentsOrderMock = jest.fn().mockResolvedValue({
//       data: null,
//       error: { message: "Failed to fetch attachments" },
//     });

//     const attachmentsInMock = jest.fn().mockReturnValue({
//       order: attachmentsOrderMock,
//     });

//     const attachmentsEqMock = jest.fn().mockReturnValue({
//       in: attachmentsInMock,
//     });

//     const attachmentsSelectMock = jest.fn().mockReturnValue({
//       eq: attachmentsEqMock,
//     });

//     mockFrom.mockImplementation((table: string) => {
//       if (table === "W26_attachments") {
//         return {
//           select: attachmentsSelectMock,
//         };
//       }

//       throw new Error(`Unexpected table: ${table}`);
//     });

//     const response = await GET({} as Request, {
//       params: Promise.resolve({ siteId: "207" }),
//     });

//     const body = await response.json();

//     expect(response.status).toBe(500);
//     expect(body).toEqual({ error: "Failed to fetch attachments" });
//   });

//   it("returns site_name as null when site lookup returns no row", async () => {
//     mockGetUser.mockResolvedValue({
//       data: {
//         user: {
//           id: "user-1",
//         },
//       },
//       error: null,
//     });

//     const attachmentsData = [
//       {
//         id: "14",
//         caption: "Cracked Tree",
//         description: "desc1",
//         content_type: "image/jpeg",
//         storage_key: "inspections/207/3226/27/file1.jpg",
//         file_size_bytes: 2433304,
//         filename: "file1.jpg",
//         site_id: "207",
//       },
//     ];

//     const attachmentsOrderMock = jest.fn().mockResolvedValue({
//       data: attachmentsData,
//       error: null,
//     });

//     const attachmentsInMock = jest.fn().mockReturnValue({
//       order: attachmentsOrderMock,
//     });

//     const attachmentsEqMock = jest.fn().mockReturnValue({
//       in: attachmentsInMock,
//     });

//     const attachmentsSelectMock = jest.fn().mockReturnValue({
//       eq: attachmentsEqMock,
//     });

//     const siteSingleMock = jest.fn().mockResolvedValue({
//       data: null,
//       error: null,
//     });

//     const siteEqMock = jest.fn().mockReturnValue({
//       single: siteSingleMock,
//     });

//     const siteSelectMock = jest.fn().mockReturnValue({
//       eq: siteEqMock,
//     });

//     mockFrom.mockImplementation((table: string) => {
//       if (table === "W26_attachments") {
//         return {
//           select: attachmentsSelectMock,
//         };
//       }

//       if (table === "W26_sites-pa") {
//         return {
//           select: siteSelectMock,
//         };
//       }

//       throw new Error(`Unexpected table: ${table}`);
//     });

//     (getSignedUrl as jest.Mock).mockResolvedValueOnce(
//       "https://signed-url.example.com/file1.jpg"
//     );

//     const response = await GET({} as Request, {
//       params: Promise.resolve({ siteId: "207" }),
//     });

//     const body = await response.json();

//     expect(response.status).toBe(200);
//     expect(body.items[0].site_name).toBeNull();
//   });

//   it("returns 500 on unexpected exception", async () => {
//     mockGetUser.mockRejectedValue(new Error("Unexpected auth crash"));

//     const response = await GET({} as Request, {
//       params: Promise.resolve({ siteId: "207" }),
//     });

//     const body = await response.json();

//     expect(response.status).toBe(500);
//     expect(body).toEqual({ error: "Failed to load gallery" });
//   });
// });

jest.mock("next/server", () => ({
  NextResponse: {
    json: jest.fn((body, init) => ({
      status: init?.status ?? 200,
      json: async () => body,
    })),
  },
}));

import { GET } from "@/app/api/sites/[siteId]/gallery/route";
import { createClient } from "@/utils/supabase/server";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

jest.mock("@/utils/supabase/server", () => ({
  createClient: jest.fn(),
}));

jest.mock("@aws-sdk/client-s3", () => ({
  S3Client: jest.fn().mockImplementation(() => ({})),
  GetObjectCommand: jest.fn().mockImplementation((input) => ({ input })),
}));

jest.mock("@aws-sdk/s3-request-presigner", () => ({
  getSignedUrl: jest.fn(),
}));

describe("GET /api/sites/[siteId]/gallery", () => {
  const mockGetUser = jest.fn();
  const mockFrom = jest.fn();

  beforeEach(() => {
    jest.clearAllMocks();

    (createClient as jest.Mock).mockResolvedValue({
      auth: {
        getUser: mockGetUser,
      },
      from: mockFrom,
    });
  });

  it("returns 400 for invalid site id", async () => {
    const response = await GET({} as Request, {
      params: Promise.resolve({ siteId: "abc" }),
    });

    const body = await response.json();

    expect(response.status).toBe(400);
    expect(body).toEqual({ error: "Invalid site id" });
  });

  it("returns 400 when site id is missing", async () => {
    const response = await GET({} as Request, {
      params: Promise.resolve({ siteId: "" }),
    });

    const body = await response.json();

    expect(response.status).toBe(400);
    expect(body).toEqual({ error: "Invalid site id" });
  });

  it("returns 401 when user is unauthorized", async () => {
    mockGetUser.mockResolvedValue({
      data: { user: null },
      error: null,
    });

    const response = await GET({} as Request, {
      params: Promise.resolve({ siteId: "207" }),
    });

    const body = await response.json();

    expect(response.status).toBe(401);
    expect(body).toEqual({ error: "Unauthorized" });
  });

  it("returns 401 when auth errors", async () => {
    mockGetUser.mockResolvedValue({
      data: { user: null },
      error: { message: "Auth failed" },
    });

    const response = await GET({} as Request, {
      params: Promise.resolve({ siteId: "207" }),
    });

    const body = await response.json();

    expect(response.status).toBe(401);
    expect(body).toEqual({ error: "Unauthorized" });
  });

  it("returns gallery items successfully", async () => {
    mockGetUser.mockResolvedValue({
      data: {
        user: {
          id: "user-1",
          user_metadata: { role: "steward" },
        },
      },
      error: null,
    });

    const attachmentsData = [
      {
        id: "14",
        caption: "Cracked Tree",
        identifier: "Tree Crack",
        content_type: "image/jpeg",
        storage_key: "inspections/207/3226/27/file1.jpg",
        file_size_bytes: 2433304,
        filename: "RiverLot56_01-31-2026_ZoeP_CrackedTree.jpg",
        site_id: "207",
        response_id: "3226",
      },
      {
        id: "15",
        caption: "Trail Damage",
        identifier: "ATV Tracks",
        content_type: "image/png",
        storage_key: "inspections/207/3227/28/file2.png",
        file_size_bytes: 123456,
        filename: "TrailDamage.png",
        site_id: "207",
        response_id: "3227",
      },
    ];

    const attachmentsOrderMock = jest.fn().mockResolvedValue({
      data: attachmentsData,
      error: null,
    });

    const attachmentsInMock = jest.fn().mockReturnValue({
      order: attachmentsOrderMock,
    });

    const attachmentsEqMock = jest.fn().mockReturnValue({
      in: attachmentsInMock,
    });

    const attachmentsSelectMock = jest.fn().mockReturnValue({
      eq: attachmentsEqMock,
    });

    const siteSingleMock = jest.fn().mockResolvedValue({
      data: { namesite: "Riverlot 56 (NA)" },
      error: null,
    });

    const siteEqMock = jest.fn().mockReturnValue({
      single: siteSingleMock,
    });

    const siteSelectMock = jest.fn().mockReturnValue({
      eq: siteEqMock,
    });

    mockFrom.mockImplementation((table: string) => {
      if (table === "W26_attachments") {
        return {
          select: attachmentsSelectMock,
        };
      }

      if (table === "W26_sites-pa") {
        return {
          select: siteSelectMock,
        };
      }

      throw new Error(`Unexpected table: ${table}`);
    });

    (getSignedUrl as jest.Mock)
      .mockResolvedValueOnce("https://signed-url.example.com/file1.jpg")
      .mockResolvedValueOnce("https://signed-url.example.com/file2.png");

    const response = await GET({} as Request, {
      params: Promise.resolve({ siteId: "207" }),
    });

    const body = await response.json();

    expect(response.status).toBe(200);

    expect(mockFrom).toHaveBeenCalledWith("W26_attachments");
    expect(mockFrom).toHaveBeenCalledWith("W26_sites-pa");

    expect(attachmentsEqMock).toHaveBeenCalledWith("site_id", 207);
    expect(attachmentsInMock).toHaveBeenCalledWith("content_type", [
      "image/jpeg",
      "image/png",
      "image/webp",
    ]);

    expect(siteEqMock).toHaveBeenCalledWith("id", 207);

    expect(body).toEqual({
      items: [
        {
          id: "14",
          caption: "Cracked Tree",
          identifier: "Tree Crack",
          filename: "RiverLot56_01-31-2026_ZoeP_CrackedTree.jpg",
          file_size_bytes: 2433304,
          site_name: "Riverlot 56 (NA)",
          response_id: "3226",
          imageUrl: "https://signed-url.example.com/file1.jpg",
        },
        {
          id: "15",
          caption: "Trail Damage",
          identifier: "ATV Tracks",
          filename: "TrailDamage.png",
          file_size_bytes: 123456,
          site_name: "Riverlot 56 (NA)",
          response_id: "3227",
          imageUrl: "https://signed-url.example.com/file2.png",
        },
      ],
    });
  });

  it("filters out items whose signed URL generation fails", async () => {
    mockGetUser.mockResolvedValue({
      data: {
        user: {
          id: "user-1",
        },
      },
      error: null,
    });

    const attachmentsData = [
      {
        id: "14",
        caption: "Cracked Tree",
        identifier: "Tree Crack",
        content_type: "image/jpeg",
        storage_key: "inspections/207/3226/27/file1.jpg",
        file_size_bytes: 2433304,
        filename: "file1.jpg",
        site_id: "207",
        response_id: "3226",
      },
      {
        id: "15",
        caption: "Trail Damage",
        identifier: "ATV Tracks",
        content_type: "image/png",
        storage_key: "inspections/207/3227/28/file2.png",
        file_size_bytes: 123456,
        filename: "file2.png",
        site_id: "207",
        response_id: "3227",
      },
    ];

    const attachmentsOrderMock = jest.fn().mockResolvedValue({
      data: attachmentsData,
      error: null,
    });

    const attachmentsInMock = jest.fn().mockReturnValue({
      order: attachmentsOrderMock,
    });

    const attachmentsEqMock = jest.fn().mockReturnValue({
      in: attachmentsInMock,
    });

    const attachmentsSelectMock = jest.fn().mockReturnValue({
      eq: attachmentsEqMock,
    });

    const siteSingleMock = jest.fn().mockResolvedValue({
      data: { namesite: "Riverlot 56 (NA)" },
      error: null,
    });

    const siteEqMock = jest.fn().mockReturnValue({
      single: siteSingleMock,
    });

    const siteSelectMock = jest.fn().mockReturnValue({
      eq: siteEqMock,
    });

    mockFrom.mockImplementation((table: string) => {
      if (table === "W26_attachments") {
        return {
          select: attachmentsSelectMock,
        };
      }

      if (table === "W26_sites-pa") {
        return {
          select: siteSelectMock,
        };
      }

      throw new Error(`Unexpected table: ${table}`);
    });

    (getSignedUrl as jest.Mock)
      .mockResolvedValueOnce("https://signed-url.example.com/file1.jpg")
      .mockRejectedValueOnce(new Error("S3 failed"));

    const response = await GET({} as Request, {
      params: Promise.resolve({ siteId: "207" }),
    });

    const body = await response.json();

    expect(response.status).toBe(200);
    expect(body.items).toHaveLength(1);
    expect(body.items[0]).toEqual({
      id: "14",
      caption: "Cracked Tree",
      identifier: "Tree Crack",
      filename: "file1.jpg",
      file_size_bytes: 2433304,
      site_name: "Riverlot 56 (NA)",
      response_id: "3226",
      imageUrl: "https://signed-url.example.com/file1.jpg",
    });
  });

  it("returns 500 when attachments query fails", async () => {
    mockGetUser.mockResolvedValue({
      data: {
        user: {
          id: "user-1",
        },
      },
      error: null,
    });

    const attachmentsOrderMock = jest.fn().mockResolvedValue({
      data: null,
      error: { message: "Failed to fetch attachments" },
    });

    const attachmentsInMock = jest.fn().mockReturnValue({
      order: attachmentsOrderMock,
    });

    const attachmentsEqMock = jest.fn().mockReturnValue({
      in: attachmentsInMock,
    });

    const attachmentsSelectMock = jest.fn().mockReturnValue({
      eq: attachmentsEqMock,
    });

    mockFrom.mockImplementation((table: string) => {
      if (table === "W26_attachments") {
        return {
          select: attachmentsSelectMock,
        };
      }

      throw new Error(`Unexpected table: ${table}`);
    });

    const response = await GET({} as Request, {
      params: Promise.resolve({ siteId: "207" }),
    });

    const body = await response.json();

    expect(response.status).toBe(500);
    expect(body).toEqual({ error: "Failed to fetch attachments" });
  });

  it("returns site_name as null when site lookup returns no row", async () => {
    mockGetUser.mockResolvedValue({
      data: {
        user: {
          id: "user-1",
        },
      },
      error: null,
    });

    const attachmentsData = [
      {
        id: "14",
        caption: "Cracked Tree",
        identifier: "Tree Crack",
        content_type: "image/jpeg",
        storage_key: "inspections/207/3226/27/file1.jpg",
        file_size_bytes: 2433304,
        filename: "file1.jpg",
        site_id: "207",
        response_id: "3226",
      },
    ];

    const attachmentsOrderMock = jest.fn().mockResolvedValue({
      data: attachmentsData,
      error: null,
    });

    const attachmentsInMock = jest.fn().mockReturnValue({
      order: attachmentsOrderMock,
    });

    const attachmentsEqMock = jest.fn().mockReturnValue({
      in: attachmentsInMock,
    });

    const attachmentsSelectMock = jest.fn().mockReturnValue({
      eq: attachmentsEqMock,
    });

    const siteSingleMock = jest.fn().mockResolvedValue({
      data: null,
      error: null,
    });

    const siteEqMock = jest.fn().mockReturnValue({
      single: siteSingleMock,
    });

    const siteSelectMock = jest.fn().mockReturnValue({
      eq: siteEqMock,
    });

    mockFrom.mockImplementation((table: string) => {
      if (table === "W26_attachments") {
        return {
          select: attachmentsSelectMock,
        };
      }

      if (table === "W26_sites-pa") {
        return {
          select: siteSelectMock,
        };
      }

      throw new Error(`Unexpected table: ${table}`);
    });

    (getSignedUrl as jest.Mock).mockResolvedValueOnce(
      "https://signed-url.example.com/file1.jpg"
    );

    const response = await GET({} as Request, {
      params: Promise.resolve({ siteId: "207" }),
    });

    const body = await response.json();

    expect(response.status).toBe(200);
    expect(body.items[0].site_name).toBeNull();
  });

  it("returns 500 on unexpected exception", async () => {
    mockGetUser.mockRejectedValue(new Error("Unexpected auth crash"));

    const response = await GET({} as Request, {
      params: Promise.resolve({ siteId: "207" }),
    });

    const body = await response.json();

    expect(response.status).toBe(500);
    expect(body).toEqual({ error: "Failed to load gallery" });
  });
});