"use client";

// Generated by ChatGPT based on the code in /api/gallery/route.ts and /api/s3/presign/route.ts, and the existing code in this file. Adjusted to fit the admin gallery page context.
import { useEffect, useState, useMemo } from "react";
import AdminNavBar from "../AdminNavBar";
import ProtectedRoute from "@/components/ProtectedRoute";
import Image from "next/image";
import { Loader2, MapPin, FileText, ImageIcon, X, Maximize2, Search, ArrowLeft } from "lucide-react";
import { useRouter } from 'next/navigation';

type GalleryItem = {
  id: string;
  response_id: string;
  question_id: string;
  caption?: string | null;
  identifier?: string | null;
  date?: string | null;
  storage_key: string;
  file_size_bytes?: number | null;
  imageUrl: string;
  caption?: string | null;
  
  // Inspection attachment fields
  response_id?: string | null;
  question_id?: string | null;
  content_type?: string | null;

  // Homepage upload fields
  date?: string | null;
  photographer?: string | null;
  identifier?: string | null;
};

export default function GalleryPage() {
  const router = useRouter();
  const [items, setItems] = useState<GalleryItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedImage, setSelectedImage] = useState<GalleryItem | null>(null);
  
  // 1. Add Search State
  const [searchQuery, setSearchQuery] = useState("");

  useEffect(() => {
    const fetchGallery = async () => {
      try {
        const res = await fetch("/api/gallery");
        const data = await res.json();
        
        const res1 = await fetch("/api/homepage-images");
        const data1 = await res1.json();

        if ((!res.ok)) {
          throw new Error(data.error || "Failed to load gallery");
        }

        if ((!res1.ok)) {
          throw new Error(data1.error || "Failed to load homepage-images");
        }

        const allItems = [
          ...(data.items || []).map((item: any) => ({
            ...item,
            _sortDate: item.created_at ?? item.date ?? "",
          })),
          ...(data1.items || []).map((item: any) => ({
            ...item,
            _sortDate: item.date ?? item.created_at ?? "",
          })),
        ].sort((a, b) => new Date(b._sortDate).getTime() - new Date(a._sortDate).getTime());
       
        setItems(allItems || []);
        console.log(allItems);
      } catch (err) {
        console.error("Gallery fetch error:", err);
      } finally {
        setLoading(false);
      }
    };

    fetchGallery();
  }, []);

  // 2. Client-side filtering logic
  const filteredItems = useMemo(() => {
    if (!searchQuery.trim()) return items;
    
    const lowerQuery = searchQuery.toLowerCase();
    
    return items.filter((item) => {
      return (
        (item.site_name || "").toLowerCase().includes(lowerQuery) ||
        (item.identifier || item.caption || "").toLowerCase().includes(lowerQuery) ||
        (item.identifier || "").toLowerCase().includes(lowerQuery) ||
        (item.date || "").toLowerCase().includes(lowerQuery) ||
        (item.filename || "").toLowerCase().includes(lowerQuery) ||
        (item.storage_key || "").toLowerCase().includes(lowerQuery)
      );
    });
  }, [items, searchQuery]);

  // Handle Back Button Navigation
  const handleBack = () => {
    const stack: string[] = JSON.parse(sessionStorage.getItem('navStack') || '[]')

    if (stack.length > 1) {
      stack.pop() // remove current page
      const previous = stack[stack.length - 1]
      stack.pop() // remove previous since we're navigating there
      sessionStorage.setItem('navStack', JSON.stringify(stack))
      router.push(previous)
    } else {
      stack.pop() // clear current page before navigating to fallback
      sessionStorage.setItem('navStack', JSON.stringify(stack))
      router.push('/sites')
    }
  }

  return (
    <ProtectedRoute requireAdmin>
      <div className="min-h-screen bg-gradient-to-br from-[#F7F2EA] via-[#E4EBE4] to-[#F7F2EA]">
        <div className="bg-gradient-to-r from-[#254431] to-[#356B43] text-white px-6 py-4 shadow-lg">
          <div className="max-w-7xl mx-auto">
            {/* Back button */}
            <button
              onClick = {handleBack}
              className="flex items-center gap-1.5 text-[#86A98A] hover:text-white transition-colors mb-4 group"
            >
              <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
              <span className="text-sm font-medium">Back</span>
            </button>
            
            <div className="flex items-center justify-between mb-3">
              {/* Left: icon + title + subtitle */}
              <div className="flex items-center gap-4">
                <Image
                  src="/images/sapaa-icon-white.png"
                  alt="SAPAA"
                  width={140}
                  height={140}
                  priority
                  className="h-16 w-auto flex-shrink-0 opacity-100 mt-1"
                />
                <div>
                  <h1 className="text-3xl font-bold mt-3">Image Gallery</h1>
                  <p className="text-[#E4EBE4] text-base mt-0.5">
                    View all uploaded inspection images and metadata
                  </p>
                </div>
              </div>
              {/* Right: navbar — rendered inline, bg overridden to transparent */}
              <div className="[&>nav]:bg-none [&>nav]:bg-transparent [&>nav]:shadow-none [&>nav]:px-0 [&>nav]:py-0">
                <AdminNavBar />
              </div>
            </div>
          </div>
        </div>

        <div className="max-w-7xl mx-auto px-6 py-8">
          
          {/* 3. Search Bar UI */}
          <div className="mb-8">
            <div className="relative w-full">
              <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <Search className="h-5 w-5 text-[#7A8075]" />
              </div>
              <input
                type="text"
                placeholder="Search by site, caption, identifier, image-name or date..."
                data-testid="admin-gallery-search-bar"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="block w-full pl-10 pr-10 py-2.5 border-2 border-[#E4EBE4] rounded-xl bg-white text-sm placeholder-[#7A8075] focus:outline-none focus:border-[#356B43] focus:ring-1 focus:ring-[#356B43] shadow-sm transition-all"
              />
              {searchQuery && (
                <button
                  type="button"
                  onClick={() => setSearchQuery("")}
                  className="absolute inset-y-0 right-0 pr-3 flex items-center"
                >
                  <X className="h-4 w-4 text-[#7A8075] hover:text-red-500 transition-colors" />
                </button>
              )}
            </div>
          </div>

          {loading ? (
            <div className="flex flex-col items-center justify-center py-20 gap-4">
              <Loader2 className="w-10 h-10 animate-spin text-[#356B43]" />
              <p className="text-[#7A8075]">Loading gallery...</p>
            </div>
          ) : filteredItems.length === 0 ? (
            <div className="text-center py-20 bg-white rounded-2xl border-2 border-dashed border-[#E4EBE4]">
              <div className="bg-[#F7F2EA] w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4">
                <Search className="text-[#7A8075]" size={32} />
              </div>
              <p className="text-[#254431] font-semibold text-lg">
                {items.length === 0 ? "No images found." : "No matching images found."}
              </p>
              {items.length > 0 && (
                <p className="text-[#7A8075] mt-1">Try adjusting your search query.</p>
              )}
            </div>
          ) : (
            <div className="grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
              {/* 4. Map over filteredItems instead of items */}
              {filteredItems.map((item) => (
                <div
                  key={`${item.response_id ? 'insp' : 'home'}-${item.id}`}
                  className="bg-white rounded-2xl border-2 border-[#E4EBE4] shadow-sm overflow-hidden hover:shadow-lg transition-all"
                >
                  <button
                    type="button"
                    onClick={() => setSelectedImage(item)}
                    className="group relative block w-full h-64 bg-[#F7F2EA] overflow-hidden"
                  >
                    <img
                      src={item.imageUrl}
                      alt={item.identifier || item.caption ||item.filename || "Inspection image"}
                      data-testid={`image-${item.identifier}`}
                      className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                    />
                    <div className="absolute inset-0 bg-black/0 group-hover:bg-black/20 transition-colors flex items-center justify-center">
                      <div className="opacity-0 group-hover:opacity-100 transition-opacity bg-white/90 rounded-full p-3 shadow-md">
                        <Maximize2 className="w-5 h-5 text-[#254431]" />
                      </div>
                    </div>
                  </button>

                  <div className="p-4 space-y-3">
                    <div className="text-sm text-[#7A8075] flex items-center gap-2">
                      <MapPin className="w-4 h-4" />
                      <span>{item.site_name || "Unknown site"}</span>
                    </div>

                    <div className="text-sm text-[#7A8075] flex items-start gap-2">
                      <ImageIcon className="w-4 h-4 mt-0.5" />
                      <div>
                        <p className="font-semibold text-[#254431]">
                          {item.identifier || item.caption || "No caption"}
                        </p>
                      </div>
                    </div>

                    <div className="text-sm text-[#7A8075] flex items-start gap-2">
                        <FileText className="w-4 h-4 mt-0.5" />
                        <div>
                          <p className="text-[#254431] font-medium">
                            {item.identifier || "No identifier"}
                          </p>
                          <p className="text-xs text-[#7A8075] mt-0.5">
                            {item.date || "No date"}
                          </p>
                        </div>
                      </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {selectedImage && (
          <div
            className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4 md:p-8"
            onClick={() => setSelectedImage(null)}
          >
            <div
              className="relative w-full max-w-6xl bg-white rounded-2xl shadow-2xl overflow-hidden"
              onClick={(e) => e.stopPropagation()}
            >
              <button
                type="button"
                onClick={() => setSelectedImage(null)}
                className="absolute top-4 right-4 z-10 bg-white/90 hover:bg-white text-[#254431] rounded-full p-2 shadow-md"
              >
                <X className="w-5 h-5" />
              </button>

              <div className="grid lg:grid-cols-[minmax(0,1fr)_360px]">
                <div className="bg-black flex items-center justify-center min-h-[300px] max-h-[85vh] overflow-auto">
                  <img
                    src={selectedImage.imageUrl}
                    alt={selectedImage.identifier || selectedImage.caption || selectedImage.filename || "Inspection image"}
                    className="max-w-full max-h-[85vh] object-contain"
                  />
                </div>

                <div className="p-6 bg-white space-y-5 border-l border-[#E4EBE4]">
                  <div>
                    <p className="text-xs uppercase tracking-wide text-[#7A8075] mb-1">
                      Site
                    </p>
                    <p className="text-lg font-semibold text-[#254431]">
                      {selectedImage.site_name || "Unknown site"}
                    </p>
                  </div>

                  <div>
                    <p className="text-xs uppercase tracking-wide text-[#7A8075] mb-1">
                      Caption
                    </p>
                    <p className="text-base font-medium text-[#254431]">
                      {selectedImage.caption || "No caption"}
                    </p>
                  </div>

                  <div>
                    <p className="text-xs uppercase tracking-wide text-[#7A8075] mb-1">
                      Identifier
                    </p>
                    <p className="text-sm text-[#4B5563] leading-6">
                      {selectedImage.identifier || "No identifier"}
                    </p>
                  </div>

                  <div>
                    <p className="text-xs uppercase tracking-wide text-[#7A8075] mb-1">
                      Date
                    </p>
                    <p className="text-sm text-[#4B5563] leading-6">
                      {selectedImage.date || "No date"}
                    </p>
                  </div>

                  <div>
                    <p className="text-xs uppercase tracking-wide text-[#7A8075] mb-1">
                      Filename
                    </p>
                    <p className="text-sm text-[#4B5563] break-all">
                      {selectedImage.filename}
                    </p>
                  </div>

                  <div>
                    <p className="text-xs uppercase tracking-wide text-[#7A8075] mb-1">
                      Storage Path
                    </p>
                    <p className="text-sm text-[#4B5563] break-all">
                      {selectedImage.storage_key}
                    </p>
                  </div>

                  <div className="pt-2">
                    <a
                      href={selectedImage.imageUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center justify-center rounded-xl bg-[#254431] text-white px-4 py-2.5 font-medium hover:bg-[#356B43] transition-colors"
                    >
                      Open full image in new tab
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </ProtectedRoute>
  );
}