//Generated by ChatGPT on 2026-03-22 based on AdminGallery.test.tsx
import AdminGalleryPage from "@/app/admin/gallery/page";
import "@testing-library/jest-dom";
import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import { createClient } from "@/utils/supabase/server";


jest.mock("@/utils/supabase/server", () => ({
  createClient: jest.fn(),
}));


jest.mock("next/navigation", () => ({
  useRouter: () => ({
    push: jest.fn(),
    back: jest.fn(),
  }),
}));

jest.mock("../../app/admin/AdminNavBar", () => () => <div>AdminNavBarMock</div>);


const mockGetUser = jest.fn();
const mockFrom = jest.fn();

beforeEach(() => {
  jest.clearAllMocks();

  (createClient as jest.Mock).mockResolvedValue({
    auth: {
      getUser: mockGetUser,
    },
    from: mockFrom,
  });

  // simulate logged-in admin
  mockGetUser.mockResolvedValue({
    data: {
      user: {
        id: "admin-1",
        user_metadata: { role: "admin" },
      },
    },
    error: null,
  });
});

describe("Admin Gallery Integration", () => {
  beforeEach(() => {
    jest.clearAllMocks();

    global.fetch = jest.fn((url: string) => {
      // Homepage uploads
      if (url.includes("/api/homepage-images")) {
        return Promise.resolve({
          ok: true,
          json: async () => ({
            items: [
              {
                id: 1,
                site_id: 207,
                site_name: "Clyde Fen",
                date: "2098-01-23",
                photographer: "Bob Suruncle",
                identifier: "ATV Tract",
                caption: "ATV tracks visible through wetland area",
                filename:
                  "ClydeFen-2098-01-23-BobSuruncle-ATVTract-a1b2c3d4.jpg",
                imageUrl: "https://example.com/1.jpg",
              },
            ],
          }),
        } as Response);
      }

      // Inspection uploads
      if (url.includes("/api/site-images")) {
        return Promise.resolve({
          ok: true,
          json: async () => ({
            items: [
              {
                id: 2,
                site_id: 208,
                site_name: "Riverlot 56 (NA)",
                response_id: 3265,
                photographer: "Raiyana Rahman",
                identifier: "Ski Trails",
                caption: "Cross country ski trails",
                filename:
                  "Riverlot56NA-2026-01-31-RaiyanaRahman-SkiTrails-aa05346a.jpg",
                imageUrl: "https://example.com/2.jpg",
              },
            ],
          }),
        } as Response);
      }

      return Promise.reject(new Error(`Unhandled fetch: ${url}`));
    }) as jest.Mock;
  });

  it("renders all media files with full metadata (admin view)", async () => {
    render(<AdminGalleryPage />);

    await waitFor(() => {
      expect(screen.getByText(/image gallery/i)).toBeInTheDocument();
    });

   
    expect(screen.getByText("Clyde Fen")).toBeInTheDocument();
    expect(screen.getByText("Riverlot 56 (NA)")).toBeInTheDocument();

    //identifier must show (NOT caption)
    expect(screen.getByText("ATV Tract")).toBeInTheDocument();
    expect(screen.getByText("Ski Trails")).toBeInTheDocument();

    // caption still stored + visible
    expect(
      screen.getByText("ATV tracks visible through wetland area")
    ).toBeInTheDocument();

    // photographer shown
    expect(screen.getByText("Bob Suruncle")).toBeInTheDocument();
    expect(screen.getByText("Raiyana Rahman")).toBeInTheDocument();

    //date shown
    expect(screen.getByText("2098-01-23")).toBeInTheDocument();

    // filename format (SAPAA naming convention)
    expect(
      screen.getByText(
        "ClydeFen-2098-01-23-BobSuruncle-ATVTract-a1b2c3d4.jpg"
      )
    ).toBeInTheDocument();
  });

  it("filters media by identifier (search test)", async () => {
    render(<AdminGalleryPage />);

    await waitFor(() => {
      expect(screen.getByText("ATV Tract")).toBeInTheDocument();
    });

    fireEvent.change(
      screen.getByPlaceholderText(
        /search by site, caption, identifier, image-name or date/i
      ),
      { target: { value: "Ski Trails" } }
    );

    // Only Ski Trails should remain
    expect(screen.getByText("Ski Trails")).toBeInTheDocument();
    expect(screen.queryByText("ATV Tract")).not.toBeInTheDocument();
  });

  it("filters media by site name", async () => {
    render(<AdminGalleryPage />);

    await waitFor(() => {
      expect(screen.getByText("Clyde Fen")).toBeInTheDocument();
    });

   
    fireEvent.change(
      screen.getByPlaceholderText(
        /search by site, caption, identifier, image-name or date/i
      ),
      { target: { value: "Clyde Fen" } }
    );

    expect(screen.getByText("Clyde Fen")).toBeInTheDocument();
    expect(screen.queryByText("Riverlot 56 (NA)")).not.toBeInTheDocument();
  });

  it("ensures every media item is linked to a site", async () => {
    render(<AdminGalleryPage />);

    await waitFor(() => {
      expect(screen.getByText("Clyde Fen")).toBeInTheDocument();
    });

    const siteNames = screen.getAllByText(/Fen|Riverlot/);
    expect(siteNames.length).toBeGreaterThan(0);
  });

  it("handles empty gallery state", async () => {
    (global.fetch as jest.Mock).mockResolvedValueOnce({
      ok: true,
      json: async () => ({ items: [] }),
    });

    render(<AdminGalleryPage />);

    await waitFor(() => {
      expect(screen.getByText(/no images found/i)).toBeInTheDocument();
    });
  });
});