// Generated by Claude

import React from 'react';
import { render, screen, fireEvent, waitFor, act } from '@testing-library/react';
import UserNavBar, { navigate } from '@/components/HeaderDropdown';
import * as auth from '@/services/auth';
import * as HeaderDropdown from '@/components/HeaderDropdown';      

jest.mock('next/navigation', () => ({
  usePathname: jest.fn(() => '/sites'),
  useRouter: jest.fn(() => ({ push: jest.fn() })),
}));

jest.mock('@/services/auth', () => ({
  logout: jest.fn(),
}));

jest.mock('@/utils/supabase/client', () => ({
  createClient: jest.fn(() => ({
    auth: {
      getSession: jest.fn().mockResolvedValue({
        data: {
          session: {
            user: {
              email: 'test@example.com',
              user_metadata: { role: 'steward', full_name: 'Test User', avatar_url: '' },
            },
          },
        },
      }),
    },
  })),
}));

describe('UserNavBar - logout button', () => {
  let navigateSpy: jest.SpyInstance;

  beforeEach(() => {
    jest.clearAllMocks();
    navigateSpy = jest.spyOn(HeaderDropdown, 'navigate').mockImplementation(() => {});
  });

  afterEach(() => {
    navigateSpy.mockRestore();
  });

  const openMenu = () => {
    fireEvent.click(screen.getByTitle('Open menu'));
  };

  it('renders the logout button when menu is open', async () => {
    await act(async () => { render(<UserNavBar />); });
    openMenu();
    expect(screen.getByText('Logout')).toBeInTheDocument();
  });

  it('calls logout() when logout button is clicked', async () => {
    (auth.logout as jest.Mock).mockResolvedValueOnce(undefined);
    await act(async () => { render(<UserNavBar />); });
    openMenu();

    fireEvent.click(screen.getByText('Logout'));

    await waitFor(() => {
      expect(auth.logout).toHaveBeenCalledTimes(1);
    });
  });

  it('redirects to /login after logout', async () => {
    (auth.logout as jest.Mock).mockResolvedValueOnce(undefined);
    await act(async () => { render(<UserNavBar />); });
    openMenu();

    fireEvent.click(screen.getByText('Logout'));

    await waitFor(() => {
      expect(navigateSpy).toHaveBeenCalledWith('/login');
    });
  });

  it('closes the menu when logout is clicked', async () => {
    (auth.logout as jest.Mock).mockResolvedValueOnce(undefined);
    await act(async () => { render(<UserNavBar />); });
    openMenu();

    fireEvent.click(screen.getByText('Logout'));

    await waitFor(() => {
      expect(screen.queryByText('Home')).not.toBeInTheDocument();
    });
  });
});