import { NextResponse } from "next/server";
import { createClient } from "@/utils/supabase/server";
import { S3Client, GetObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

//Generated by ChatGPT, based on my original code for admin endpoint. Original code is in webapp/app/api/gallery/route.ts


interface Attachment {
  id: string;
  response_id: string;
  question_id: string;
  caption?: string | null;
  description?: string | null;
  storage_key: string;
  content_type: string;
  file_size_bytes?: number | null;
  filename: string;
  site_id: string;
}

const REGION = process.env.AWS_REGION!;
const BUCKET = process.env.AWS_S3_BUCKET_NAME!;

const s3 = new S3Client({
  region: REGION,
  credentials: {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID!,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY!,
  },
});

const ALLOWED_IMAGE_TYPES = ["image/jpeg", "image/png", "image/webp"];

export async function GET(
  _req: Request,
  { params }: { params: Promise<{ siteId: string }> }
) {
  try {
    const { siteId } = await params;

    console.log("=== /api/sites/[siteId]/gallery START ===");
    console.log("siteId from params:", siteId);

    const numericSiteId = Number(siteId);

    if (!siteId || Number.isNaN(numericSiteId)) {
      return NextResponse.json(
        { error: "Invalid site id" },
        { status: 400 }
      );
    }

    const supabase = await createClient();

    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { data: attachments, error: attachmentsError } = await supabase
      .from("W26_attachments")
      .select(`
        id,
        caption,
        description,
        content_type,
        storage_key,
        file_size_bytes,
        filename,
        site_id
      `)
      .eq("site_id", numericSiteId)
      .in("content_type", ALLOWED_IMAGE_TYPES)
      .order("id", { ascending: false });

    if (attachmentsError) {
      return NextResponse.json(
        { error: attachmentsError.message },
        { status: 500 }
      );
    }

    const { data: site } = await supabase
      .from("W26_sites-pa")
      .select("namesite")
      .eq("id", siteId)
      .single();

    const items = await Promise.all(
      (attachments || []).map(async (attachment) => {
        let imageUrl: string | null = null;

        try {
          const command = new GetObjectCommand({
            Bucket: BUCKET,
            Key: attachment.storage_key,
          });

          imageUrl = await getSignedUrl(s3, command, {
            expiresIn: 3600,
          });
        } catch (err) {
          console.error("Signed URL error:", err);
        }

        return {
          id: attachment.id,
          caption: attachment.caption,
          description: attachment.description,
          filename: attachment.filename,
          file_size_bytes: attachment.file_size_bytes,
          site_name: site?.namesite ?? null,
          imageUrl,
        };
      })
    );

    const validItems = items.filter((item) => item.imageUrl);

    return NextResponse.json({
      items: validItems,
    });

  } catch (err) {
    console.error("Site gallery error:", err);
    return NextResponse.json(
      { error: "Failed to load gallery" },
      { status: 500 }
    );
  }
}