name: Webapp CI
on:
  push:
    branches:
      - main
      - Sprint-2
      - Sprint-3
      - Sprint-4
      - Sprint-5
  pull_request:
    branches:
      - '**'    # Run tests on PRs from any branch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-webapp:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: webapp
        run: npm ci || npm install

      - name: Run Webapp tests
        working-directory: webapp
        run: npm test -- --forceExit

  deploy:
      needs: test-webapp
      runs-on: self-hosted
      if: github.ref == 'refs/heads/Sprint-3' && github.event_name == 'push'
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
    
        - name: Deploy with Docker Compose
          working-directory: /home/ubuntu/deploy
          run: |
            docker compose down
            docker compose up -d --build
